-- Tablas clinicas de la admision
-- Generado desde sihosrecuperacion (copia de SIHOS) el 2026-09-25.
-- MISMOS nombres y columnas que SIHOS para poder exportar. Solo estructura, sin datos.
-- Sin llaves foraneas: la app inserta en orden padre -> hijo.

SET NAMES latin1;
SET SESSION sql_mode = 'NO_ENGINE_SUBSTITUTION';  -- SIHOS usa fechas 0000-00-00
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `Admision`;
CREATE TABLE `Admision` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001' COMMENT 'Codigo de Institucion',
  `ConsAdmi` varchar(12) NOT NULL COMMENT 'Consecutivo de Admision por Institucion',
  `TipoDocu` char(2) NOT NULL DEFAULT '' COMMENT 'Tipo de Documento del Usuario',
  `NumeUsua` varchar(20) NOT NULL DEFAULT '' COMMENT 'Numero de Documento del Usuario',
  `ValoEdad` int(3) DEFAULT '0' COMMENT 'Valor Numerico de la Edad al Ingreso',
  `UnidEdad` char(1) DEFAULT 'A' COMMENT 'Unidad de la Edad al Ingreso A=Años, M=Mese, D=Dias',
  `GrupoAte` char(1) DEFAULT 'O' COMMENT 'Grupo de Atencion de la Admision',
  `CodiAdmi` varchar(6) DEFAULT NULL COMMENT 'Codigo de Entidad Administradora de CodiAdmi',
  `TipoUsua` int(1) DEFAULT NULL COMMENT 'Tipo de Usuario',
  `TipoAfil` char(1) DEFAULT NULL COMMENT 'Tipo de Afiliacion',
  `CodiEstr` char(1) DEFAULT NULL COMMENT 'Categoria o Nivel acorde con AdmiEstr',
  `NumeCont` varchar(15) NOT NULL DEFAULT '' COMMENT 'Numero de Contrato de la Admision',
  `NumeAuto` varchar(50) DEFAULT NULL COMMENT 'Numero de Autorizaion General',
  `NumePoli` varchar(30) NOT NULL,
  `FechIngr` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha de Ingreso o de Admision',
  `HoraIngr` time NOT NULL DEFAULT '00:00:00' COMMENT 'Hora de Ingreso o de Admision',
  `EstaIngr` int(1) DEFAULT NULL COMMENT 'Estado al Ingreso del Paciente',
  `ViaIngre` int(1) DEFAULT NULL COMMENT 'Via de Ingreso del Paciente',
  `VienRefe` int(1) DEFAULT NULL COMMENT 'Viene Referido Si/No',
  `LugaRefe` varchar(30) DEFAULT NULL COMMENT 'Lugar de donde viene referido',
  `EspeRefe` char(3) DEFAULT NULL COMMENT 'Especialidad de Referencia',
  `CoinRefe` varchar(12) DEFAULT '' COMMENT 'Codigo institucion referencia',
  `CoadRefe` varchar(12) DEFAULT '' COMMENT 'Admision institucion referencia',
  `DiagIngr` char(8) DEFAULT '' COMMENT 'Diagnostico de Ingreso',
  `CodiRel1` char(8) DEFAULT '' COMMENT 'Diagnostico Relacionado 1',
  `CodiRel2` char(8) DEFAULT '' COMMENT 'Diagnostico Relacionado 2',
  `CodiRel3` char(8) DEFAULT '' COMMENT 'Diagnostico Relacionado 3',
  `CodiRel4` char(8) DEFAULT '' COMMENT 'Diagnostico Relacionado 4',
  `TipoAten` int(1) NOT NULL DEFAULT '0' COMMENT 'Tipo de Atencion del Servicio de Ingreso',
  `CodiServ` char(3) DEFAULT NULL COMMENT 'Servicio de Ingreso en la Admision',
  `CentCost` varchar(6) NOT NULL COMMENT 'Codigo centro de costo origen',
  `CodiCama` varchar(10) DEFAULT NULL COMMENT 'Cama de Ingreso acorde con el servicio de Ingreso',
  `MotiCons` text COMMENT 'Motivo de Ingreso a Urgencias',
  `ServEgre` char(3) DEFAULT NULL COMMENT 'Servicio Actual y/o de Egreso',
  `CentEgre` varchar(6) NOT NULL COMMENT 'Codigo centro de costo actual',
  `CamaActu` varchar(10) DEFAULT '' COMMENT 'Cama Actual o de Egreso acorde con el Servicio Actual o de Egreso',
  `FechEgre` date DEFAULT NULL COMMENT 'Fecha del Egreso',
  `HoraEgre` time DEFAULT NULL COMMENT 'Hora del Egreso',
  `CausExte` char(2) DEFAULT NULL COMMENT 'Causa Externa segun Resolucion 3374',
  `EntoAten` bigint(20) unsigned DEFAULT NULL COMMENT 'lista tipos 11',
  `CondUsua` int(1) DEFAULT NULL COMMENT 'Condicion de la Usuaria',
  `MensPart` timestamp DEFAULT NULL COMMENT 'Fecha última de menstruación',
  `DesFum` int(1) DEFAULT '0' COMMENT 'Desconoce FUM',
  `DudaMensPart` bigint(20) DEFAULT NULL COMMENT 'Lista tipo 30, Duda de la fecha de la ultima menstruacion',
  `FechPart` timestamp DEFAULT NULL COMMENT 'Fecha posible de parto',
  `FecUltEmb` timestamp DEFAULT NULL COMMENT 'Fecha ultimo embarazo',
  `TipoAcom` int(1) DEFAULT NULL COMMENT 'Tipo de Acompañante',
  `IdenAcom` varchar(50) NOT NULL DEFAULT '' COMMENT 'identificacion del acompañante',
  `DocuAcom` char(2) NOT NULL DEFAULT '' COMMENT 'Tipo de Documento Acompañante',
  `Parentes` int(2) DEFAULT '1' COMMENT 'Parentesco del acompañante',
  `NombAcom` varchar(80) DEFAULT NULL COMMENT 'Nombre del Acompañante',
  `DireAcom` varchar(40) DEFAULT NULL COMMENT 'Direccion del Acompañante',
  `TeleAcom` varchar(10) DEFAULT NULL COMMENT 'Tlefono del Acompañante',
  `CoinHias` varchar(12) DEFAULT NULL COMMENT 'Institucion donde se atiende a la pareja',
  `CoadHias` varchar(12) DEFAULT NULL COMMENT 'Admision donde se atiende a la pareja',
  `Reingres` int(1) NOT NULL DEFAULT '0' COMMENT 'Es una Admision de Reingreso Estadistico Si/No',
  `ClasTria` int(1) DEFAULT NULL COMMENT 'Clasificacion del Triage en la Admision',
  `ConsCita` int(20) DEFAULT '0' COMMENT 'Numero Consecutivo de la Cita a partir de la cual se crea esta Admision',
  `CodiDocu` varchar(4) DEFAULT '' COMMENT 'Documento Liquidación con la cual se Atendió',
  `NumeFact` int(20) DEFAULT '0' COMMENT 'Numero de Liquidación con la cual se Atendió',
  `ConsDeFa` int(11) DEFAULT '0' COMMENT 'Consecutivo del Detalle de Liquidacion',
  `Cerrado` int(1) DEFAULT '2' COMMENT 'Admision con Historia Cerrada',
  `CodiDora` int(11) DEFAULT NULL COMMENT 'Código dorado Resolución 347',
  `FechCier` date DEFAULT '0000-00-00' COMMENT 'Fecha de Cierre',
  `HoraCier` time DEFAULT '00:00:00' COMMENT 'Hora de Cierre',
  `UsuaCier` varchar(12) DEFAULT '' COMMENT 'Usuario que Cerro',
  `Anulado` int(1) DEFAULT '2' COMMENT 'Admision con Historia Anulada',
  `CausAnul` int(2) NOT NULL DEFAULT '0' COMMENT 'Causa de Anulacion',
  `NotaAnul` varchar(255) DEFAULT '' COMMENT 'Nota de Anulacion',
  `FechAnul` date DEFAULT '0000-00-00' COMMENT 'Fecha de Anulacion',
  `HoraAnul` time DEFAULT '00:00:00' COMMENT 'Hora de Anulacion',
  `UsuaAnul` varchar(12) DEFAULT '' COMMENT 'Usuario que Anulo',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha de Creacion de Registro',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00' COMMENT 'Hora de Creacion de registro',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha de Modificacion del Registro',
  `HoraModi` time NOT NULL DEFAULT '00:00:00' COMMENT 'Hora de Modificacion del Registro',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  `ConsLabo` int(2) DEFAULT '0' COMMENT 'Consecutivo Laboratorio Clinico',
  KEY `Admision_ibfk_9` (`NumeUsua`),
  KEY `idk_Admision_CodiCama` (`CodiCama`),
  KEY `idk_Admision_CodiInst` (`CodiInst`,`ServEgre`,`Cerrado`,`Anulado`),
  KEY `Idx_Admision_CamaActu` (`CamaActu`),
  KEY `idx_Admision_CantAdm_202` (`CodiInst`,`TipoDocu`,`NumeUsua`,`FechIngr`,`CodiAdmi`,`ConsAdmi`),
  KEY `idx_Admision_CausExte` (`CausExte`),
  KEY `idx_Admision_Cerrado_Anulado` (`Cerrado`,`Anulado`),
  KEY `idx_admision_codiadmi` (`CodiAdmi`),
  KEY `Idx_Admision_CodiDocu` (`CodiDocu`),
  KEY `idx_Admision_CodiInst` (`CodiInst`),
  KEY `idx_Admision_CodiInst_2` (`CodiInst`,`CodiAdmi`,`NumeCont`),
  KEY `idx_Admision_CodiInst_3` (`CodiInst`,`CodiAdmi`,`CodiEstr`,`TipoAten`,`TipoAfil`),
  KEY `idx_admision_codiinst_consadmi_servegre` (`CodiInst`,`ConsAdmi`,`ServEgre`),
  KEY `idx_admision_codiinst_consadmi_serv_fech_hora` (`CodiInst`,`ConsAdmi`,`ServEgre`,`FechIngr`,`HoraIngr`),
  KEY `idx_Admision_codiinst_consadmi_unidedad_valoedad` (`CodiInst`,`ConsAdmi`,`UnidEdad`,`ValoEdad`),
  KEY `idx_admision_codiinst_consamdi_fechingr` (`CodiInst`,`ConsAdmi`,`FechIngr`),
  KEY `idx_admision_codiinst_servegre_fech_hora` (`CodiInst`,`ServEgre`,`FechIngr`,`HoraIngr`),
  KEY `idx_admision_codinst_servegre` (`CodiInst`,`ServEgre`),
  KEY `idx_Admision_CodiServ` (`CodiServ`,`TipoDocu`,`NumeUsua`),
  KEY `idx_Admision_ConsAdmi` (`ConsAdmi`),
  KEY `Idx_Admision_ConsCita` (`ConsCita`),
  KEY `idx_Admision_ConsCita_CodiInst` (`ConsCita`,`CodiInst`),
  KEY `idx_Admision_EntoAten` (`EntoAten`),
  KEY `idx_Admision_EstaIngr` (`EstaIngr`),
  KEY `idx_Admision_FechDigi_cover` (`FechDigi`,`CodiInst`,`ConsAdmi`,`CodiAdmi`,`NumeCont`,`TipoUsua`,`CodiServ`,`ServEgre`,`UsuaDigi`,`TipoDocu`,`NumeUsua`,`UnidEdad`,`ValoEdad`,`FechIngr`,`HoraIngr`,`HoraDigi`),
  KEY `idx_Admision_FechIngr` (`FechIngr`),
  KEY `idx_Admision_HoraIngr` (`HoraIngr`),
  KEY `Idx_Admision_NumeFact` (`NumeFact`),
  KEY `idx_Admision_paciente_fecha_anulado` (`TipoDocu`,`NumeUsua`,`FechIngr`,`Anulado`),
  KEY `idx_Admision_paciente_fecha_Ingr` (`CodiInst`,`TipoDocu`,`NumeUsua`,`FechIngr`),
  KEY `idx_Admision_ServEgre` (`CodiInst`,`ServEgre`,`ConsAdmi`,`TipoDocu`,`NumeUsua`),
  KEY `idx_Admision_TipoAcom` (`TipoAcom`),
  KEY `idx_Admision_TipoDocu` (`TipoDocu`,`NumeUsua`),
  KEY `idx_Admision_TipoDocu_NumeUsua_FechIngr` (`TipoDocu`,`NumeUsua`,`FechIngr`),
  KEY `idx_Admision_TipoUsua` (`TipoUsua`),
  KEY `idx_Admision_UnidEdad` (`UnidEdad`),
  KEY `idx_Admision_ValoEdad` (`ValoEdad`),
  KEY `idx_Admision_ViaIngre` (`ViaIngre`),
  KEY `idx_adm_inst_cons_serv_fechhora` (`CodiInst`,`ConsAdmi`,`ServEgre`,`FechIngr`,`HoraIngr`),
  KEY `idx_adm_inst_fechhora_serv_cons` (`CodiInst`,`FechIngr`,`HoraIngr`,`ServEgre`,`ConsAdmi`),
  KEY `idx_adm_inst_fech_hora_serv_flags_cons` (`CodiInst`,`FechIngr`,`HoraIngr`,`ServEgre`,`Cerrado`,`Anulado`,`ConsAdmi`),
  KEY `idx_adm_inst_fech_hora_serv_flags_cons_paci_cama` (`CodiInst`,`FechIngr`,`HoraIngr`,`ServEgre`,`Cerrado`,`Anulado`,`ConsAdmi`,`TipoDocu`,`NumeUsua`,`CamaActu`),
  KEY `idx_adm_inst_serv_fech_hora_flags_cons_paci_cama` (`CodiInst`,`ServEgre`,`FechIngr`,`HoraIngr`,`Cerrado`,`Anulado`,`ConsAdmi`,`TipoDocu`,`NumeUsua`,`CamaActu`),
  KEY `idx_adm_inst_serv_flags_fechhora_cons_paci_cama` (`CodiInst`,`ServEgre`,`Cerrado`,`Anulado`,`FechIngr`,`HoraIngr`,`ConsAdmi`,`TipoDocu`,`NumeUsua`,`CamaActu`),
  KEY `idx_CodiInst_UsuaDigi` (`CodiInst`,`UsuaDigi`),
  PRIMARY KEY (`CodiInst`,`ConsAdmi`),
  KEY `ServEgre` (`ServEgre`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `Triage`;
CREATE TABLE `Triage` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '734430295601' COMMENT 'Codigo de Institucion',
  `ConsAdmi` varchar(12) NOT NULL DEFAULT '' COMMENT 'Codigo de la Admision',
  `ConsTria` int(10) NOT NULL DEFAULT '0' COMMENT 'Consecutivo por admision de Triage',
  `TipoDocu` char(2) NOT NULL DEFAULT '' COMMENT 'Tipo de documento del Paciente',
  `NumeUsua` varchar(20) NOT NULL DEFAULT '' COMMENT 'Numero de Documento del paciente',
  `FechTria` date DEFAULT NULL COMMENT 'Fecha de Realizacion de Triage',
  `HoraTria` time DEFAULT NULL COMMENT 'Hora de Realizacion de Triage',
  `MotiCons` text COMMENT 'Motivo de Consulta',
  `HallClin` text COMMENT 'Hallazgos Clinicos',
  `CodiDiag` char(8) DEFAULT '' COMMENT 'Codigo del diagnostico',
  `ClasTria` int(1) DEFAULT NULL COMMENT 'Clasificacion de Triage (I,II,III,IV,V)',
  `CondTria` varchar(30) NOT NULL DEFAULT '',
  `Conducta` text COMMENT 'Conducta dependiente de tipo de ClasTriag de la tabla CondTria',
  `Realizad` int(1) DEFAULT '0',
  `CodiAdmi` varchar(6) DEFAULT NULL COMMENT 'Codigo de Administradora',
  `NumeCont` varchar(15) DEFAULT NULL COMMENT 'Numero de Contrato de la Administradora',
  `TipoUsua` int(1) DEFAULT NULL COMMENT 'Tipo de Usuario',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  `CodiCons` varchar(5) DEFAULT NULL COMMENT 'Codigo de Consultorio',
  KEY `CodiInst` (`CodiInst`),
  KEY `ConsTria` (`ConsTria`),
  KEY `idx_Triage_ClasTria` (`ClasTria`),
  KEY `idx_Triage_CodiDiag` (`CodiDiag`),
  KEY `idx_Triage_ConsAdmi` (`ConsAdmi`),
  KEY `idx_triage_inst_admi_codicons` (`CodiInst`,`ConsAdmi`,`CodiCons`),
  KEY `idx_triage_reporte` (`CodiInst`,`FechTria`,`HoraTria`,`CodiAdmi`,`NumeCont`,`TipoUsua`,`TipoDocu`,`NumeUsua`,`CodiDiag`),
  KEY `NumeUsua` (`NumeUsua`),
  PRIMARY KEY (`CodiInst`,`ConsAdmi`,`ConsTria`),
  KEY `TipoDocu` (`TipoDocu`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `SignVita`;
CREATE TABLE `SignVita` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001' COMMENT 'Codigo de Institucion',
  `ConsAdmi` varchar(12) NOT NULL DEFAULT '',
  `ConsSign` int(3) NOT NULL DEFAULT '0',
  `ConsEvol` int(3) DEFAULT '0',
  `CodiModu` int(2) NOT NULL DEFAULT '0',
  `FechToma` date NOT NULL DEFAULT '0000-00-00',
  `ConsCons` int(20) DEFAULT '0',
  `id_clap` int(11) DEFAULT '0' COMMENT 'Identificador unico de la CLAP',
  `ConsClap` varchar(20) DEFAULT NULL,
  `ConsTrPa` int(2) DEFAULT NULL,
  `Valotiem` int(2) DEFAULT NULL,
  `UnidTiem` char(1) DEFAULT NULL,
  `HoraToma` time NOT NULL DEFAULT '00:00:00',
  `Peso` decimal(5,2) DEFAULT '0.00',
  `Talla` decimal(10,1) DEFAULT '0.0',
  `MasaCorp` decimal(5,2) DEFAULT '0.00',
  `PeriCefa` decimal(5,2) DEFAULT '0.00' COMMENT 'Perimetro Cefalico en cm.',
  `Pulso` int(11) DEFAULT '0',
  `Respirac` int(11) DEFAULT '0',
  `Temperat` decimal(4,2) DEFAULT '0.00',
  `PANume` int(3) DEFAULT '0',
  `PADeno` int(3) DEFAULT '0',
  `FetoCard` int(3) DEFAULT '0',
  `Saturaci` decimal(5,2) DEFAULT '0.00',
  `SintResp` int(1) DEFAULT '2' COMMENT 'Sintomatico Respiratorio (SR)',
  `SintPiel` int(1) DEFAULT '2' COMMENT 'Sintomatico de Piel (SNP)',
  `UnidEdad` char(1) NOT NULL DEFAULT 'A',
  `ValoEdad` int(3) NOT NULL DEFAULT '0',
  `PeriCint` decimal(5,2) DEFAULT '0.00' COMMENT 'Perimetro De Cintura',
  `PeriCade` decimal(5,2) DEFAULT '0.00' COMMENT 'Perimetro De Cadera',
  `ResCXC` decimal(5,2) DEFAULT '0.00' COMMENT 'Resultado Entre Cintura y Cadera',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  `Dolor` decimal(10,2) DEFAULT '0.00',
  `TM` int(11) DEFAULT '0',
  `Oximetria` int(4) DEFAULT NULL,
  `GlucMetr` int(3) DEFAULT '0' COMMENT 'Glucometria',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  KEY `FechToma` (`FechToma`),
  KEY `idx_SignVita_admi` (`CodiInst`,`ConsAdmi`,`FechToma`),
  KEY `idx_SignVita_clap_trpa` (`id_clap`,`ConsTrPa`),
  KEY `idx_SignVita_clap_trpa_fecha_hora` (`id_clap`,`ConsTrPa`,`FechDigi`,`HoraDigi`),
  KEY `idx_SignVita_CodiModu` (`CodiModu`),
  KEY `idx_SignVita_ConsAdmi` (`CodiInst`,`ConsAdmi`),
  PRIMARY KEY (`CodiInst`,`ConsAdmi`,`ConsSign`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `RipsCons`;
CREATE TABLE `RipsCons` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001' COMMENT 'Codigo Institucion',
  `ConsAdmi` varchar(12) NOT NULL DEFAULT '' COMMENT 'Consecutivo de Admision',
  `ConsCons` int(20) NOT NULL DEFAULT '0' COMMENT 'Consecutivo de Consulta',
  `CodiModu` int(2) NOT NULL COMMENT 'Modulo',
  `FechCons` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha de Consulta',
  `HoraCons` time NOT NULL DEFAULT '00:00:00' COMMENT 'Hora de Consulta',
  `UsuaCons` varchar(12) DEFAULT '' COMMENT 'Usuario que Inicia Consulta',
  `TipoCons` varchar(15) NOT NULL DEFAULT '' COMMENT 'Codigo del Procedimiento',
  `FinaCons` char(2) NOT NULL COMMENT 'Finalidad de la Consulta',
  `MotiCons` text COMMENT 'Motivo de Consulta',
  `EnfeActu` text COMMENT 'Enfermedad Actual',
  `ReviSist` text COMMENT 'Revision por Sistemas',
  `SintResp` int(1) DEFAULT '2' COMMENT 'Sintomatico Respiratorio ',
  `SintPiel` int(1) DEFAULT '2' COMMENT 'Sintomatico de Piel ',
  `SintNerv` int(1) DEFAULT '2' COMMENT 'Sintomatico Nervioso ',
  `TubeMult` int(1) NOT NULL DEFAULT '2' COMMENT 'Tuberculosis Multidrogoresistente',
  `TipoLepr` int(1) NOT NULL DEFAULT '0' COMMENT 'Lepra',
  `PeriAbdo` int(3) DEFAULT NULL COMMENT 'Perimetro Abdominal',
  `PeriTorx` int(3) DEFAULT '0' COMMENT 'Perimetro Torax',
  `LaboImag` text COMMENT 'Laboratorio e Imagenes',
  `DereSexu` int(1) DEFAULT NULL COMMENT 'Derechos sexuales  reproductivos',
  `InteVoEm` int(1) DEFAULT NULL COMMENT 'Interrupcion voluntaria del embarazo',
  `TipoDiag` int(1) DEFAULT NULL COMMENT 'Tipo de Diagnostico',
  `TipoDia1` int(1) DEFAULT '0' COMMENT 'Tipo de diagnostico relacionado1',
  `TipoDia2` int(1) DEFAULT '0' COMMENT 'Tipo de diagnostico relacionado2',
  `TipoDia3` int(1) DEFAULT '0' COMMENT 'Tipo de diagnostico relacionado3',
  `TipoDia4` int(1) DEFAULT '0' COMMENT 'Tipo de diagnostico relacionado4',
  `CodiDiag` char(8) DEFAULT NULL COMMENT 'Diagnostico Principal',
  `CodiRel1` char(8) DEFAULT '' COMMENT 'Diagnostico Relacionado 1',
  `CodiRel2` char(8) DEFAULT '' COMMENT 'Diagnostico Relacionado 2',
  `CodiRel3` char(8) DEFAULT '' COMMENT 'Diagnostico Relacionado 3',
  `CodiRel4` char(8) DEFAULT '' COMMENT 'Diagnostico Relacionado 4',
  `CodiEspe` char(3) DEFAULT NULL COMMENT 'Especialidad',
  `ObseReco` text COMMENT 'Plan de Manejo y Recomendaciones',
  `EstaReal` int(1) NOT NULL DEFAULT '0' COMMENT 'Esta Realizado',
  `ConsCita` int(20) DEFAULT '0' COMMENT 'Consecutivo de Cita',
  `FechCier` date DEFAULT '0000-00-00' COMMENT 'Fecha de Cierre o Fin de la Consulta',
  `HoraCier` time DEFAULT '00:00:00' COMMENT 'Hora de Cierre o Fin de la Consulta',
  `UsuaCier` varchar(12) DEFAULT '' COMMENT 'Usuario que Cerro la Consulta',
  `DestSali` int(1) DEFAULT '4' COMMENT 'Destino a la Salida',
  `EstaDest` int(1) DEFAULT '2' COMMENT 'Estado de Paciente en el Destino a la Salida',
  `UsuaAsis` varchar(20) DEFAULT '' COMMENT 'Usuario Asistencial de la Consulta',
  `EstaCarg` int(1) NOT NULL DEFAULT '0' COMMENT 'Esta Cargado',
  `NumeOrde` int(20) DEFAULT '0' COMMENT 'Numero de Orden',
  `Item` int(2) DEFAULT '0' COMMENT 'Numero de Item',
  `CodiDocu` varchar(4) DEFAULT '' COMMENT 'Documento Liquidación',
  `NumeLiqu` int(20) DEFAULT '0' COMMENT 'Numero de Liquidacion',
  `ConsDeFa` int(20) DEFAULT '0' COMMENT 'Consecutivo Detalle de Liquidacion',
  `CentCost` varchar(50) DEFAULT '' COMMENT 'Centro de Costos',
  `ServEgre` varchar(6) DEFAULT NULL COMMENT 'Tipo de servicio ',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  `CodiServ` varchar(6) DEFAULT NULL COMMENT 'Tipo de servicio',
  `CentEgre` char(6) DEFAULT NULL,
  `Conducta` bigint(20) unsigned DEFAULT NULL COMMENT 'Listas Tipos 33',
  `Accinme` varchar(150) DEFAULT NULL COMMENT 'Selector multiple Acciones inmediatas',
  `ContCuid` varchar(150) DEFAULT NULL COMMENT 'Selector multiple Continuidad del cuidado',
  `EstaCodo` bigint(20) DEFAULT NULL COMMENT 'lista tipo 47',
  `Especif` text COMMENT 'Especificaciones del profesional codigo dorado',
  `ObserCd` text COMMENT 'Observaciones seccion codigo dorado',
  KEY `ConsCita` (`ConsCita`),
  KEY `idx_RipsCons` (`CodiInst`,`ConsAdmi`,`FechCons`),
  KEY `idx_RipsCons_admi` (`CodiInst`,`ConsAdmi`,`EstaReal`,`FechCons`),
  KEY `idx_RipsCons_CodiDiag` (`CodiDiag`),
  KEY `idx_RipsCons_CodiInst_ConsAdmi` (`CodiInst`,`ConsAdmi`),
  KEY `idx_ripscons_codiinst_consadmi_codidocu_tipocons` (`CodiInst`,`ConsAdmi`,`CodiDocu`,`TipoCons`),
  KEY `idx_RipsCons_CodiInst_ConsAdmi_EstaReal_1` (`CodiInst`,`ConsAdmi`,`EstaReal`),
  KEY `idx_RipsCons_CodiModu` (`CodiModu`),
  KEY `idx_RipsCons_Conducta` (`Conducta`),
  KEY `idx_RipsCons_ConsAdmi_CodiInst` (`ConsAdmi`,`CodiInst`),
  KEY `idx_RipsCons_ConsAdmi_CodiInstRDA` (`ConsAdmi`,`CodiInst`),
  KEY `idx_RipsCons_FechCons` (`FechCons`),
  KEY `idx_RipsCons_FinaCons` (`FinaCons`),
  KEY `idx_RipsCons_inst_admi_usua` (`CodiInst`,`ConsAdmi`,`UsuaCons`),
  KEY `idx_RipsCons_TipoCons` (`TipoCons`),
  KEY `idx_RipsCons_TipoDiag` (`TipoDiag`),
  KEY `idx_rips_inst_admi_conscons_estado_usua` (`CodiInst`,`ConsAdmi`,`ConsCons`,`EstaReal`,`UsuaAsis`),
  PRIMARY KEY (`CodiInst`,`ConsAdmi`,`ConsCons`),
  KEY `SintNerv` (`SintNerv`),
  KEY `SintPiel` (`SintPiel`),
  KEY `SintResp` (`SintResp`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `EstaGene`;
CREATE TABLE `EstaGene` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001',
  `ConsAdmi` varchar(12) NOT NULL DEFAULT '',
  `ConsEsGe` int(9) NOT NULL DEFAULT '0',
  `CodiModu` int(2) NOT NULL,
  `ConsCons` int(20) NOT NULL DEFAULT '0',
  `ConsHoPr` int(11) DEFAULT '0',
  `ReviSist` text,
  `Fecha` date NOT NULL DEFAULT '0000-00-00',
  `Hora` time NOT NULL DEFAULT '00:00:00',
  `EstaGene` text,
  `Cabeza` int(1) DEFAULT NULL,
  `CabeDesc` text,
  `Cuello` int(1) DEFAULT NULL,
  `CuelDesc` text,
  `CardPulm` int(1) DEFAULT NULL,
  `CardDesc` text,
  `Abdomen` int(1) DEFAULT NULL,
  `AbdoDesc` text,
  `GeniUrin` int(1) DEFAULT NULL,
  `GeniDesc` text,
  `Extremid` int(1) DEFAULT NULL,
  `ExtrDesc` text,
  `Neurolog` int(1) DEFAULT NULL,
  `NeurDesc` text,
  `Nariz` int(1) DEFAULT NULL,
  `NariDesc` text,
  `Oidos` int(1) DEFAULT NULL,
  `OidoDesc` text,
  `Boca` int(1) DEFAULT NULL,
  `BocaDesc` text,
  `Ojos` int(1) DEFAULT '1',
  `OjosDesc` text,
  `Piel` int(1) DEFAULT '1',
  `PielDesc` text,
  `Ano` int(1) DEFAULT NULL,
  `AnoDesc` text,
  `OsteMusc` int(1) DEFAULT NULL,
  `OsteDesc` text,
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  KEY `idx_EstaGene_admi` (`CodiInst`,`ConsAdmi`,`FechDigi`),
  KEY `idx_EstaGene_CodiModu` (`CodiModu`),
  KEY `idx_EstaGene_ConsAdmi` (`CodiInst`,`ConsAdmi`),
  PRIMARY KEY (`CodiInst`,`ConsAdmi`,`ConsEsGe`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `Antecede`;
CREATE TABLE `Antecede` (
  `id` bigint(20) NOT NULL auto_increment COMMENT 'Identificador único de la tabla',
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001',
  `ConsAdmi` varchar(12) NOT NULL,
  `ConsAnte` int(2) NOT NULL,
  `TipoDocu` char(2) NOT NULL,
  `NumeUsua` varchar(20) NOT NULL,
  `CodiModu` int(2) NOT NULL,
  `ConsCons` int(20) NOT NULL DEFAULT '0',
  `Familiar` int(1) DEFAULT NULL,
  `FamiDesc` text,
  `Personal` int(1) DEFAULT NULL,
  `PersDesc` text,
  `Patologi` int(1) DEFAULT NULL,
  `PatoDesc` text,
  `Obstetri` int(1) DEFAULT NULL,
  `ObstDesc` text,
  `Quirurgi` int(1) DEFAULT NULL,
  `QuirDesc` text,
  `ToxiAler` int(1) DEFAULT NULL,
  `ToxiDesc` text,
  `AlerSiNo` int(11) DEFAULT '0' COMMENT 'Antecedente alergÃ©nico, si o no',
  `AlerDesc` text COMMENT 'DescripciÃ³n del antecedente alergÃ©nico',
  `Fisiolog` int(1) DEFAULT NULL,
  `FisiDesc` text,
  `Alimenta` int(1) DEFAULT NULL,
  `AlimDesc` text,
  `Traumati` int(1) DEFAULT NULL,
  `TrauDesc` text,
  `Farmacol` int(1) DEFAULT NULL,
  `FactRies` int(1) DEFAULT NULL COMMENT 'factor de riesgo',
  `FarmDesc` text,
  `Oculares` int(1) DEFAULT NULL,
  `OculDesc` text,
  `MetoPlan` int(1) DEFAULT '2',
  `MetoDesc` int(1) DEFAULT NULL,
  `Ginecolo` int(1) DEFAULT '2',
  `GineDesc` text,
  `Icterico` int(1) DEFAULT '2' COMMENT 'Ictericos',
  `IcteDesc` text,
  `Discrasi` int(1) DEFAULT '2' COMMENT 'Disprasicos',
  `DiscDesc` text,
  `TBC` int(1) DEFAULT '2' COMMENT 'TBC',
  `TBCDesc` text,
  `LUES` int(1) DEFAULT '2' COMMENT 'LUES',
  `LUESDesc` text,
  `Asma` int(1) DEFAULT '2' COMMENT 'Asma',
  `AsmaDesc` text,
  `IMAO` int(1) DEFAULT '2' COMMENT 'IMAO',
  `IMAODesc` text,
  `Esteroid` int(1) DEFAULT '2' COMMENT 'Esteroides',
  `EsteDesc` text,
  `Hipotens` int(1) DEFAULT '2' COMMENT 'Hipotensores',
  `HipoDesc` text,
  `Insulina` int(1) DEFAULT '2' COMMENT 'Insulina',
  `InsuDesc` text,
  `BBloquea` int(1) DEFAULT '2' COMMENT 'B/Bloqueadores',
  `BBloDesc` text,
  `Otros` int(1) DEFAULT '2',
  `OtroDesc` text,
  `FechRegl` date DEFAULT '0000-00-00' COMMENT 'Fecha de ultima regla',
  `FechPart` date DEFAULT '0000-00-00' COMMENT 'Fecha probable del parto',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  `Andropo` int(11) DEFAULT NULL,
  `Consilia` int(11) DEFAULT NULL,
  `AndroDesc` text,
  `ConsiDesc` text,
  KEY `CodiInst` (`CodiInst`,`ConsAdmi`,`ConsAnte`),
  KEY `idx_Antecede_admi` (`CodiInst`,`ConsAdmi`,`FechDigi`),
  KEY `idx_Antecede_Alimenta` (`Alimenta`),
  KEY `idx_Antecede_CodiModu` (`CodiModu`),
  KEY `idx_Antecede_ConsAdmi` (`CodiInst`,`ConsAdmi`),
  KEY `idx_Antecede_Familiar` (`Familiar`),
  KEY `idx_Antecede_Farmacol` (`Farmacol`),
  KEY `idx_Antecede_Fisiolog` (`Fisiolog`),
  KEY `idx_Antecede_NumeFact` (`TipoDocu`),
  KEY `idx_Antecede_Obstetri` (`Obstetri`),
  KEY `idx_Antecede_Patologi` (`Patologi`),
  KEY `idx_Antecede_Personal` (`Personal`),
  KEY `idx_Antecede_Quirurgi` (`Quirurgi`),
  KEY `idx_Antecede_TipoDocu` (`TipoDocu`,`NumeUsua`),
  KEY `idx_Antecede_ToxiAler` (`ToxiAler`),
  KEY `idx_Antecede_Traumati` (`Traumati`),
  PRIMARY KEY (`CodiInst`,`ConsAdmi`,`ConsAnte`),
  KEY `TipoDocu` (`TipoDocu`,`NumeUsua`),
  UNIQUE KEY `uk_antecede_id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `EncaData`;
CREATE TABLE `EncaData` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '',
  `ConsAdmi` varchar(12) NOT NULL DEFAULT '',
  `TipoObje` int(2) NOT NULL DEFAULT '0',
  `ConsData` int(20) NOT NULL DEFAULT '0',
  `CodiModu` int(2) DEFAULT NULL,
  `Fecha` date DEFAULT NULL,
  `Hora` time DEFAULT NULL,
  `UsuaAsis` varchar(20) DEFAULT '',
  `FechDigi` date DEFAULT '0000-00-00',
  `HoraDigi` time DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date DEFAULT '0000-00-00',
  `HoraModi` time DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  PRIMARY KEY (`CodiInst`,`ConsAdmi`,`TipoObje`,`ConsData`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `DetaData`;
CREATE TABLE `DetaData` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '',
  `ConsAdmi` varchar(12) NOT NULL DEFAULT '',
  `TipoObje` int(2) NOT NULL DEFAULT '0',
  `ConsData` int(20) NOT NULL DEFAULT '0',
  `CodiItem` int(20) NOT NULL DEFAULT '0',
  `CodiSino` int(1) DEFAULT NULL,
  `CodiEsta` int(1) DEFAULT '0',
  `Texto` text,
  `Valor1` int(20) DEFAULT NULL,
  `Valor2` int(20) DEFAULT NULL,
  `FechDigi` date DEFAULT '0000-00-00',
  `HoraDigi` time DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date DEFAULT '0000-00-00',
  `HoraModi` time DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  KEY `Idx_DetaData_EncaData` (`CodiInst`,`ConsAdmi`,`TipoObje`,`ConsData`),
  PRIMARY KEY (`CodiInst`,`ConsAdmi`,`TipoObje`,`ConsData`,`CodiItem`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `EncaOrde`;
CREATE TABLE `EncaOrde` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001' COMMENT 'Codigo Institucion',
  `ConsAdmi` varchar(12) NOT NULL DEFAULT '' COMMENT 'Consecutivo de Admision',
  `ConsOrde` int(2) NOT NULL DEFAULT '0' COMMENT 'Consecutivo de Orden por Admision',
  `CodiModu` int(2) NOT NULL COMMENT 'Codigo Modulos',
  `CodiServ` char(3) DEFAULT '0' COMMENT 'Codigo del Servicio',
  `ConsCons` int(20) NOT NULL DEFAULT '0' COMMENT 'Consecutivo Consulta',
  `Consecut` int(20) NOT NULL COMMENT 'Consecutivo General de Orden por Institucion',
  `CodiFina` char(2) DEFAULT '10' COMMENT 'Finalidad',
  `Fecha` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha Orden',
  `Hora` time NOT NULL DEFAULT '00:00:00' COMMENT 'Hora Orden',
  `ObseOrde` text COMMENT 'Observacion General de la Orden',
  `CodiDiag` char(8) DEFAULT '' COMMENT 'Codigo de diagnostico',
  `CodiRel1` char(8) DEFAULT '' COMMENT 'Codigo relacionado 1',
  `CodiRel2` char(8) DEFAULT '' COMMENT 'Codigo relacionado 2',
  `CodiRel3` char(8) DEFAULT '' COMMENT 'Codigo relacionado 3',
  `CodiRel4` char(8) DEFAULT '' COMMENT 'Codigo relacionado 4',
  `OrdeSali` int(1) DEFAULT '0' COMMENT 'Es Orden Ambulatoria. Interfaz Labo.',
  `OrdeAmbu` int(1) DEFAULT '0' COMMENT 'Es una orden Ambulatoria. Sihos',
  `ImprOrde` int(1) DEFAULT '0' COMMENT 'Si ya fue impreso por primera vez o no.',
  `Autoriza` int(1) DEFAULT '0',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  KEY `CodiFina` (`CodiFina`),
  KEY `CodiServ` (`CodiServ`),
  KEY `idx_EncaOrde_CodiModu` (`CodiModu`),
  KEY `idx_encaorde_codinst_consadmi_fecha` (`CodiInst`,`ConsAdmi`,`Fecha`,`ConsOrde`),
  KEY `idx_EncaOrde_ConsAdmi` (`CodiInst`,`ConsAdmi`),
  KEY `idx_encaorde_fecha` (`Fecha`),
  PRIMARY KEY (`CodiInst`,`ConsAdmi`,`ConsOrde`),
  KEY `UsuaDigi` (`UsuaDigi`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `DetaOrde`;
CREATE TABLE `DetaOrde` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001' COMMENT 'Codigo Institucion',
  `ConsAdmi` varchar(12) NOT NULL DEFAULT '' COMMENT 'Cnsecutivo de Admision',
  `ConsOrde` int(2) NOT NULL DEFAULT '0' COMMENT 'Consecutivo de Orden por Admision',
  `Item` int(2) NOT NULL DEFAULT '0' COMMENT 'Numero de Renglon o Item',
  `CodiModu` int(2) NOT NULL COMMENT 'Codigo Modulo que Digito',
  `CodiProc` varchar(15) NOT NULL DEFAULT '' COMMENT 'Codigo del Procedimiento',
  `CodiFina` varchar(2) DEFAULT NULL COMMENT 'Finalidad del Procedimiento',
  `CantSumi` int(5) NOT NULL DEFAULT '0' COMMENT 'Cantidad Ordenada',
  `ObseProc` varchar(70) DEFAULT '',
  `CantReal` int(5) NOT NULL DEFAULT '0' COMMENT 'Cantidad Realizada o Ejecutada',
  `CantFact` int(5) NOT NULL DEFAULT '0' COMMENT 'Cantidad Liquidada',
  `CodiDocu` varchar(4) DEFAULT '' COMMENT 'Codigo Documento en donde se Liquida',
  `NumeLiqu` int(20) NOT NULL DEFAULT '0' COMMENT 'Numero del Documento en donde se Liquida',
  `ConsDeFa` int(11) NOT NULL DEFAULT '0' COMMENT 'Consecutivo de Detalle o Renglon de DetaFact',
  `TipoHora` varchar(10) DEFAULT '',
  `CodiServ` varchar(6) NOT NULL DEFAULT '0' COMMENT 'Codigo de servicio',
  `CodiProf` varchar(12) DEFAULT '' COMMENT 'Login del Profesional ',
  `FechSusp` date DEFAULT '0000-00-00' COMMENT 'Fecha de suspension',
  `HoraSusp` time DEFAULT '00:00:00' COMMENT 'Hora de suspension',
  `UsuaSusp` varchar(12) DEFAULT '' COMMENT 'Usuario que suspendio',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '2000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  KEY `CodiInst` (`CodiInst`,`ConsAdmi`),
  KEY `CodiProc` (`CodiProc`),
  KEY `CodiProf` (`CodiProf`),
  KEY `idx_detaorde` (`CodiInst`,`ConsAdmi`,`ConsOrde`,`CodiProc`,`CantReal`,`CantFact`,`FechSusp`),
  KEY `idx_DetaOrde_admi_proc` (`CodiInst`,`ConsAdmi`,`CodiProc`),
  KEY `idx_DetaOrde_ConsAdmi` (`CodiInst`,`ConsAdmi`,`ConsOrde`),
  KEY `idx_DetaOrde_inst_admi_or_item` (`CodiInst`,`ConsAdmi`,`ConsOrde`,`Item`),
  PRIMARY KEY (`CodiInst`,`ConsAdmi`,`ConsOrde`,`Item`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `EncaPres`;
CREATE TABLE `EncaPres` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001' COMMENT 'Codigo Institucion',
  `ConsAdmi` varchar(12) NOT NULL DEFAULT '' COMMENT 'Consecutivo de Admision',
  `ConsPres` int(2) NOT NULL COMMENT 'Consecutivo de Prescripcion por Admision',
  `TipoPres` int(1) NOT NULL DEFAULT '1' COMMENT 'Tipo de prescripcion 1=regular 2=control',
  `CodiModu` int(2) NOT NULL DEFAULT '0' COMMENT 'Codigo de Modulo',
  `CodiServ` char(3) DEFAULT '0' COMMENT 'Codigo del Servicio',
  `CentCost` varchar(6) DEFAULT NULL COMMENT 'Centro de costo donde se realiza la solicitud del medicamento',
  `ConsCons` int(20) NOT NULL DEFAULT '0' COMMENT 'Consecutivo de Consulta',
  `Consecut` int(20) NOT NULL DEFAULT '0' COMMENT 'Consecutivo Global de Prescripcion',
  `Fecha` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha Prescripcion',
  `Hora` time NOT NULL DEFAULT '00:00:00' COMMENT 'Hora Prescripcion',
  `FechEntr` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha de Entrega de la Prescripcion',
  `ObseOrde` text COMMENT 'Observaciones Generales de la Prescripcion',
  `PresSali` int(1) NOT NULL DEFAULT '1' COMMENT 'Es Prescripcion de Salida/Domiciliaria',
  `CodiDiag` char(8) DEFAULT '' COMMENT 'Diagnostico Principal',
  `CodiRel1` char(8) DEFAULT '' COMMENT 'Diagnostico Relacionado 1',
  `CodiRel2` char(8) DEFAULT '' COMMENT 'Diagnostico Relacionado 2',
  `CodiRel3` char(8) DEFAULT '' COMMENT 'Diagnostico Relacionado 3',
  `CodiRel4` char(8) DEFAULT '' COMMENT 'Diagnostico Relacionado 4',
  `ImprOrde` int(1) DEFAULT '0' COMMENT 'Para saber si ya se imprimio la preinscripcion',
  `PersEntr` varchar(15) DEFAULT NULL COMMENT 'Persona encargada de la entrega del medicamento de control',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  KEY `idk_EncaPres_CodiServ` (`CodiServ`),
  KEY `idx_EncaPres_CodiModu` (`CodiModu`),
  KEY `idx_EncaPres_ConsAdmi` (`CodiInst`,`ConsAdmi`),
  KEY `idx_EncaPres_Fecha` (`Fecha`),
  KEY `idx_EncaPres_fecha_codiinst_consadmi_conspres` (`Fecha`,`CodiInst`,`ConsAdmi`,`ConsPres`),
  KEY `idx_EncaPres_MediCont` (`ConsPres`),
  KEY `idx_encapres_pressali` (`CodiInst`,`ConsAdmi`,`PresSali`),
  KEY `idx_ep_fecha` (`CodiInst`,`ConsAdmi`,`ConsPres`,`Fecha`),
  PRIMARY KEY (`CodiInst`,`ConsAdmi`,`ConsPres`),
  KEY `TipoPres` (`TipoPres`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `DetaPres`;
CREATE TABLE `DetaPres` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001' COMMENT 'Codigo Institucion',
  `ConsAdmi` varchar(12) NOT NULL DEFAULT '' COMMENT 'Consecutivo Admision',
  `ConsPres` int(2) NOT NULL DEFAULT '0' COMMENT 'Consecutivo de Prescripcion por Admision',
  `Item` int(2) NOT NULL DEFAULT '0' COMMENT 'Consecutivo del Detalle de Prescripcion',
  `CodiModu` int(2) NOT NULL COMMENT 'Codigo de Modulo',
  `CodiFina` char(2) DEFAULT NULL COMMENT 'Finalidad del Suministro',
  `CodiSumi` varchar(20) DEFAULT NULL COMMENT 'Codigo del Suministro',
  `Horas` decimal(5,2) DEFAULT '0.00' COMMENT 'Numero de Horas para Oxigeno',
  `LitrMinu` int(11) DEFAULT '0' COMMENT 'Litros por minuto para Oxigeno',
  `CantSumi` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Cantidad en Unidades Menores',
  `Contenid` decimal(10,2) DEFAULT '0.00' COMMENT 'Contenido en Unidades Menores en la Unidad Mayor',
  `CodiVia` int(1) NOT NULL DEFAULT '1' COMMENT 'Via de Suministro',
  `HoraApli` int(2) NOT NULL DEFAULT '0' COMMENT 'Frecuencia de Aplicacion - Cada - Tabla HoraApli',
  `HoraInic` time NOT NULL DEFAULT '00:00:00' COMMENT 'Hora Inicial a partir de la cual se hace el Plan de Aplicacion por Enfermeria',
  `CantFrec` tinyint(2) unsigned DEFAULT '0' COMMENT 'Cantidad de frecuencia',
  `TiemFrec` tinyint(1) unsigned DEFAULT '0' COMMENT 'Tiempo de frecuencia (1= Hora(s), 2 = DÃƒÂ­a(s), 3= Mes(es))',
  `CantPeDu` tinyint(2) unsigned DEFAULT '0' COMMENT 'Cantidad de periodo de duraciÃƒÂ³n',
  `TiemPeDu` tinyint(1) unsigned DEFAULT '0' COMMENT 'Tiempo periodo de duraciÃƒÂ³n (1= Hora(s), 2 = DÃƒÂ­a(s), 3= Mes(es))',
  `NumeDosi` int(5) NOT NULL DEFAULT '0' COMMENT 'Numero de Dosis o Aplicaciones',
  `CantTota` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Cantidad Total Solicitada en Unidades Menores',
  `CantApli` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Cantidad Aplicada en Unidades Menores',
  `CantSoli` int(5) DEFAULT '0' COMMENT 'Cantidad Solicitada a Bodega o Farmacia en Unidades Mayores',
  `CantEntr` int(5) NOT NULL DEFAULT '0' COMMENT 'Cantidad Entregada por la Bodega o Farmacia en Unidades Mayores',
  `CantDevo` int(10) NOT NULL DEFAULT '0' COMMENT 'Cantidad Devuelta a Bodega o Farmacia en Unidades Mayores',
  `PresMedi` text COMMENT 'Prescripcion Escrita del Medicamento',
  `MediPrin` int(1) DEFAULT '0' COMMENT 'Es medicamento principal (0= No, 1= Si)',
  `CantFact` int(5) NOT NULL DEFAULT '0' COMMENT 'Cantidad Liquidada en Unidades Mayores',
  `CodiDocu` varchar(4) DEFAULT '' COMMENT 'Codigo Institucion',
  `NumeLiqu` int(20) NOT NULL DEFAULT '0' COMMENT 'Codigo Institucion',
  `ConsDeFa` int(11) NOT NULL DEFAULT '0' COMMENT 'Codigo Institucion',
  `CodiServ` char(6) DEFAULT '' COMMENT 'Codigo de servicio',
  `FechSusp` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha de la Suspencion',
  `HoraSusp` time NOT NULL DEFAULT '00:00:00' COMMENT 'Hora de la Suspension',
  `UsuaSusp` varchar(12) DEFAULT '' COMMENT 'Usuario que Suspendio',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  `UnidMedi` int(2) DEFAULT NULL COMMENT 'Unidades de aplicacion Medicamentos',
  KEY `CodiInst` (`CodiInst`,`ConsAdmi`),
  KEY `CodiSumi` (`CodiSumi`),
  KEY `idx_detapres_admi` (`CodiInst`,`ConsAdmi`,`ConsPres`,`Item`,`CodiSumi`),
  KEY `idx_DetaPres_CodiInst_ConsAdmi_CodiSumi_1` (`CodiInst`,`ConsAdmi`,`CodiSumi`),
  KEY `idx_DetaPres_codiinst_consadmi_conspres_codisumi_item` (`CodiInst`,`ConsAdmi`,`ConsPres`,`CodiSumi`,`Item`),
  KEY `idx_detapres_codiinst_consadmi_numeliqu_codisumi` (`CodiInst`,`ConsAdmi`,`NumeLiqu`,`CodiSumi`),
  KEY `idx_DetaPres_CodiVia` (`CodiVia`),
  KEY `idx_DetaPres_ConsAdmi` (`CodiInst`,`ConsAdmi`,`ConsPres`),
  KEY `idx_DetaPres_HoraApli` (`HoraApli`),
  KEY `idx_DetaPres_inst_admi_pres_item` (`CodiInst`,`ConsAdmi`,`ConsPres`,`Item`),
  KEY `idx_DetaPres_join` (`CodiInst`,`ConsAdmi`,`ConsPres`,`CodiSumi`),
  KEY `Item` (`Item`),
  PRIMARY KEY (`CodiInst`,`ConsAdmi`,`ConsPres`,`Item`),
  KEY `UnidMedi` (`UnidMedi`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `HojaProc`;
CREATE TABLE `HojaProc` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001' COMMENT 'Codigo Institucion',
  `ConsAdmi` varchar(12) NOT NULL DEFAULT '' COMMENT 'Consecutivo Admision',
  `ConsHoPr` int(11) NOT NULL DEFAULT '0' COMMENT 'Consecutivo Hoja',
  `CodiModu` int(2) NOT NULL COMMENT 'Modulo',
  `MotiCons` text,
  `EnfeActu` text,
  `ConsCons` int(2) NOT NULL DEFAULT '0',
  `NumeActo` int(11) DEFAULT NULL COMMENT 'Numero del Acto Qx',
  `EsCrue` int(1) DEFAULT '0' COMMENT 'Procedimiento Cruento o Incruento',
  `TipoCiru` int(1) DEFAULT NULL COMMENT 'Tipo de Cirugia en vez de FormQuir',
  `TipoAnes` int(1) DEFAULT '1' COMMENT 'Tipo de Anestesia',
  `ViaAcces` int(1) DEFAULT NULL COMMENT 'Via de Acceso',
  `DescQuir` text COMMENT 'Descripcion Quirurgica',
  `CodiProc` varchar(15) NOT NULL DEFAULT '' COMMENT 'Codigo del Procedimiento',
  `CodiFina` char(2) NOT NULL COMMENT 'Finalidad de Procedimiento',
  `FechProc` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha Procedimiento',
  `HoraProc` time NOT NULL DEFAULT '00:00:00' COMMENT 'Hora Procedimiento',
  `TipoDiag` int(1) DEFAULT NULL COMMENT 'Tipo de Diagnostico',
  `TipoDiaR` int(1) DEFAULT '0' COMMENT 'Tipo de diagnostico relacionado1',
  `TipoDia1` int(1) DEFAULT '0' COMMENT 'Tipo de diagnostico relacionado2',
  `TipoDia2` int(1) DEFAULT '0' COMMENT 'Tipo de diagnostico relacionado3',
  `TipoDiaC` int(1) DEFAULT '0' COMMENT 'Tipo de diagnostico relacionado4',
  `DiagPrin` varchar(8) NOT NULL DEFAULT '' COMMENT 'Diagnostico Principal',
  `DiagRela` varchar(8) NOT NULL DEFAULT '' COMMENT 'Diagnostico relacionado',
  `DiagRel1` varchar(8) NOT NULL DEFAULT '' COMMENT 'Diagnostico relacionado 1',
  `DiagRel2` varchar(8) NOT NULL DEFAULT '' COMMENT 'Diagnostico relacionado 2',
  `DiagRel3` varchar(8) NOT NULL DEFAULT '' COMMENT 'Diagnostico relacionado 3',
  `DiagComp` varchar(8) NOT NULL DEFAULT '' COMMENT 'Diagnostico de complicacion',
  `IndiAdic` text COMMENT 'Observaciones',
  `CodiProf` varchar(8) DEFAULT NULL COMMENT 'Profesional',
  `UsuaAsis` varchar(8) DEFAULT NULL COMMENT 'Elaboro Procedimiento o Cirugia',
  `ProcReal` int(1) unsigned NOT NULL DEFAULT '1' COMMENT 'Indica si el procedimiento fue realizado al paciente',
  `CantProc` int(5) NOT NULL DEFAULT '0' COMMENT 'Cantidad Realizado',
  `CantFact` int(5) NOT NULL DEFAULT '0' COMMENT 'Cantidad Liquidado',
  `NumeOrde` int(20) NOT NULL DEFAULT '0' COMMENT 'Numero General de Orden que se Atiende',
  `Item` int(2) NOT NULL DEFAULT '0' COMMENT 'Item de la Orden que se Atiende',
  `CentCost` varchar(6) NOT NULL DEFAULT '0',
  `ServEgre` char(3) NOT NULL DEFAULT '0',
  `CodiDocu` varchar(4) DEFAULT '' COMMENT 'Documento Liquidacion',
  `NumeLiqu` int(20) NOT NULL DEFAULT '0' COMMENT 'Numero de Liquidacion',
  `ConsDeFa` int(11) NOT NULL DEFAULT '0' COMMENT 'Consecutivo Detalle de Liquidacion',
  `ConsCita` int(20) DEFAULT '0',
  `CodiDosi` int(2) DEFAULT NULL COMMENT 'Numero de Dosis',
  `ConsTrat` int(3) DEFAULT '0' COMMENT 'Consecutivo Tratamiento',
  `NumePiez` int(5) NOT NULL COMMENT 'Numero de Pieza',
  `CuadPiez` int(5) NOT NULL COMMENT 'Numero de Cuadrante',
  `TecnLabo` int(2) unsigned DEFAULT '1' COMMENT 'Tipo de tecnica de laboratorio',
  `FechVali` date DEFAULT '0000-00-00' COMMENT 'Fecha Validacion',
  `HoraVali` time DEFAULT '00:00:00' COMMENT 'Hora Validacion',
  `UsuaVali` varchar(12) DEFAULT '' COMMENT 'Usuario Valida',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(8) NOT NULL DEFAULT '',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(8) NOT NULL DEFAULT '',
  `CodiServ` varchar(6) NOT NULL DEFAULT '0' COMMENT 'Codigo de servicio',
  `ContRevi` int(1) DEFAULT '0' COMMENT 'Campo para validar si ha sido revisado o no la evoluciÃ³n por un especialista',
  `CentEgre` char(6) DEFAULT NULL,
  `MediRevi` varchar(8) DEFAULT NULL,
  `FechRevi` date DEFAULT NULL,
  `HoraRevi` time DEFAULT '00:00:00' COMMENT 'Hora de revisado de la evoluciÃ³n',
  `DescRevi` text COMMENT 'DescripciÃ³n o anotaciÃ³n agregada por el mÃ©dico que revisa la evoluciÃ³n del paciente',
  KEY `CodiLiqu` (`CodiDocu`,`NumeLiqu`,`ConsDeFa`),
  KEY `hp_asis_fecha_inst_admi` (`UsuaAsis`,`FechProc`,`CodiInst`,`ConsAdmi`),
  KEY `idx_HojaProc_admi_proc` (`CodiInst`,`ConsAdmi`,`CodiProc`),
  KEY `idx_HojaProc_CodiProc` (`CodiProc`),
  KEY `idx_HojaProc_ConsAdmi` (`CodiInst`,`ConsAdmi`),
  KEY `idx_HojaProc_ConsAdmi_CodiInst` (`ConsAdmi`,`CodiInst`),
  KEY `idx_HojaProc_ConsAdmi_CodiInstRDA` (`ConsAdmi`,`CodiInst`),
  KEY `idx_HojaProc_ConsTrat` (`ConsTrat`),
  KEY `idx_HojaProc_FechProc` (`FechProc`),
  KEY `idx_HojaProc_inst_admi_modu` (`CodiInst`,`ConsAdmi`,`CodiModu`),
  KEY `idx_HojaProc_pend_inst_admi` (`CodiInst`,`ConsAdmi`,`CantFact`,`CantProc`),
  KEY `idx_HojaProc_quir` (`CodiInst`,`ConsAdmi`,`NumeActo`,`TipoCiru`,`TipoAnes`),
  PRIMARY KEY (`CodiInst`,`ConsAdmi`,`ConsHoPr`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `DetaPrue`;
CREATE TABLE `DetaPrue` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001' COMMENT 'Codigo Institucion',
  `ConsAdmi` varchar(12) NOT NULL COMMENT 'Consecutivo de Admision',
  `ConsHoPr` int(11) NOT NULL DEFAULT '0' COMMENT 'Consecutivo Hoja de Procedimientos',
  `ConsPrue` int(10) NOT NULL DEFAULT '0' COMMENT 'Consecutivo de Prueba',
  `CodiProc` varchar(15) NOT NULL DEFAULT '' COMMENT 'Codigo del Procedimiento',
  `CodiPrue` int(4) NOT NULL COMMENT 'Codigo de Prueba de Laboratorio',
  `NombUnid` varchar(255) DEFAULT '' COMMENT 'Nombre de la Unidad de los valores de referencia',
  `ValoMini` char(10) DEFAULT '' COMMENT 'Valor de referencia minimo para la prueba de laboratorio',
  `ValoMaxi` char(10) DEFAULT '' COMMENT 'Valor de referencia maximo para la prueba de laboratorio',
  `Valor` text COMMENT 'Valor de la Prueba',
  `ValoRefe` text COMMENT 'Valores de Referencia.',
  `MicroOrganismo` text COMMENT 'Micro Organismo',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  `UnidPrue` char(5) DEFAULT '',
  KEY `idx_DetaPrue_CodiInst` (`CodiInst`,`ConsAdmi`,`CodiProc`),
  KEY `idx_DetaPrue_CodiProc` (`CodiProc`,`CodiPrue`),
  KEY `idx_DetaPrue_ConsAdmi` (`CodiInst`,`ConsAdmi`,`ConsHoPr`),
  PRIMARY KEY (`CodiInst`,`ConsAdmi`,`ConsHoPr`,`ConsPrue`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `HojaEnfe`;
CREATE TABLE `HojaEnfe` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001' COMMENT 'Codigo Institucion',
  `ConsAdmi` varchar(12) NOT NULL DEFAULT '' COMMENT 'Consecutivo de Admision',
  `TipoNota` int(2) NOT NULL DEFAULT '1' COMMENT 'Tipo Nota',
  `Procedim` varchar(40) DEFAULT '' COMMENT 'Descripcion del Procedimiento Consentimiento Informado',
  `ConsHoEn` int(11) NOT NULL DEFAULT '0' COMMENT 'Consecutivo Hoja de Enfermeria',
  `CodiModu` int(2) NOT NULL DEFAULT '0' COMMENT 'Codigo Modulo',
  `CodiServ` char(3) DEFAULT '0' COMMENT 'Codigo del Servicio',
  `ConsCons` int(20) NOT NULL DEFAULT '0' COMMENT 'Consecutivo Consulta',
  `FechNota` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha de Nota',
  `HoraNota` time NOT NULL DEFAULT '00:00:00' COMMENT 'Hora de Nota',
  `NotaEnfe` text COMMENT 'Texto de la Nota',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  `Reviza` int(1) DEFAULT '0',
  `UsuaRevi` varchar(12) DEFAULT '',
  `HoraRevi` time DEFAULT '00:00:00',
  `FechRevi` date NOT NULL DEFAULT '0000-00-00',
  `DeclLeid` int(1) DEFAULT '0' COMMENT 'El paciente declarÃ³ haber leÃ­do el documento 0:no 1:si (consentimiento, TipoNota=5)',
  `FechDecl` date DEFAULT NULL COMMENT 'Fecha en que se registrÃ³ la declaraciÃ³n de lectura',
  `HoraDecl` time DEFAULT NULL COMMENT 'Hora en que se registrÃ³ la declaraciÃ³n de lectura',
  `UsuaDecl` varchar(12) DEFAULT NULL COMMENT 'Usuario que acompaÃ±Ã³/registrÃ³ la declaraciÃ³n de lectura',
  KEY `idx_HojaEnfe_CodiModu` (`CodiModu`),
  KEY `idx_HojaEnfe_ConsAdmi` (`CodiInst`,`ConsAdmi`),
  KEY `idx_HojaEnfe_TipoNota` (`TipoNota`),
  PRIMARY KEY (`CodiInst`,`ConsAdmi`,`ConsHoEn`,`TipoNota`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `HojaMedi`;
CREATE TABLE `HojaMedi` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001' COMMENT 'Codigo Institucion',
  `ConsAdmi` varchar(12) NOT NULL DEFAULT '' COMMENT 'Consecutivo de Admision',
  `ConsHoMe` int(3) NOT NULL DEFAULT '0' COMMENT 'Consecutivo Hoja de Medicamentos',
  `CodiModu` int(2) NOT NULL DEFAULT '0' COMMENT 'Codigo Modulo',
  `CodiServ` char(3) DEFAULT '0' COMMENT 'Codigo del Servicio',
  `FechMedi` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha de Medicamento',
  `HoraMedi` time NOT NULL DEFAULT '00:00:00' COMMENT 'Hora de Medicamento',
  `FechPlan` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha Planeado',
  `HoraPlan` time NOT NULL DEFAULT '00:00:00' COMMENT 'Hora Planeado',
  `CodiMedi` varchar(20) DEFAULT NULL COMMENT 'Codigo del Medicamento',
  `ViaAdmi` int(1) DEFAULT NULL COMMENT 'Via de Administracion',
  `EstaApli` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Esta Aplicado',
  `CantMedi` double NOT NULL DEFAULT '0' COMMENT 'Cantidad de Medicamento',
  `UnidMedi` int(2) NOT NULL DEFAULT '1' COMMENT 'Unidad de Medida',
  `IndiAdic` varchar(255) DEFAULT NULL COMMENT 'Observaciones',
  `EsFact` int(1) NOT NULL DEFAULT '1' COMMENT 'Es Facturable',
  `CantFact` int(5) NOT NULL DEFAULT '0' COMMENT 'Cantidad Liquidada',
  `UsuaAsis` varchar(20) DEFAULT '',
  `NumeOrde` int(20) DEFAULT '0',
  `Item` int(2) DEFAULT '0',
  `CodiDocu` varchar(4) DEFAULT '' COMMENT 'Documento Liquidacion',
  `NumeLiqu` int(20) DEFAULT '0' COMMENT 'Numero del Documento',
  `ConsDeFa` int(11) DEFAULT '0' COMMENT 'Detalle de Liquidacion',
  `ValoUnit` decimal(13,2) NOT NULL DEFAULT '0.00',
  `ValoTota` decimal(13,2) NOT NULL DEFAULT '0.00',
  `EstaFact` int(1) NOT NULL DEFAULT '0',
  `Despacha` int(1) NOT NULL DEFAULT '0',
  `DispMedi` int(20) NOT NULL DEFAULT '0',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  `Correctos` int(11) NOT NULL DEFAULT '0',
  `CentCost` varchar(6) NOT NULL DEFAULT '0',
  KEY `idx_hojamedi` (`CodiInst`,`ConsAdmi`,`NumeOrde`,`CodiMedi`),
  KEY `idx_HojaMedi_admi` (`CodiInst`,`ConsAdmi`,`EstaApli`,`CodiMedi`),
  KEY `idx_HojaMedi_CodiInst_ConsAdmi_CodiMedi_1` (`CodiInst`,`ConsAdmi`,`CodiMedi`,`EstaApli`),
  KEY `idx_HojaMedi_CodiMedi` (`CodiMedi`),
  KEY `idx_HojaMedi_ConsAdmi` (`CodiInst`,`ConsAdmi`),
  KEY `idx_HojaMedi_inst_admi_conshome` (`CodiInst`,`ConsAdmi`,`ConsHoMe`),
  KEY `idx_HojaMedi_join` (`CodiInst`,`ConsAdmi`,`NumeOrde`,`CodiMedi`,`Item`),
  KEY `idx_HojaMedi_order` (`FechPlan`,`HoraPlan`),
  KEY `idx_HojaMedi_UnidMedi` (`UnidMedi`),
  PRIMARY KEY (`CodiInst`,`ConsAdmi`,`ConsHoMe`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `HojaMate`;
CREATE TABLE `HojaMate` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001',
  `ConsAdmi` varchar(12) NOT NULL DEFAULT '',
  `ConsHoMa` int(3) NOT NULL DEFAULT '0',
  `CodiModu` int(2) NOT NULL DEFAULT '0',
  `CodiServ` char(3) DEFAULT '0' COMMENT 'Codigo del Servicio',
  `FechMate` date NOT NULL DEFAULT '0000-00-00',
  `HoraMate` time NOT NULL DEFAULT '00:00:00',
  `CodiMate` varchar(20) DEFAULT NULL,
  `UnidMate` char(2) NOT NULL DEFAULT '00',
  `EsFact` int(1) NOT NULL DEFAULT '1',
  `IndiAdic` varchar(255) DEFAULT NULL,
  `CantMate` double NOT NULL DEFAULT '0',
  `CantFact` double NOT NULL DEFAULT '0',
  `NumeOrde` int(20) DEFAULT '0',
  `Item` int(2) DEFAULT '0',
  `CentCost` varchar(6) NOT NULL DEFAULT '0',
  `CodiDocu` varchar(4) DEFAULT '' COMMENT 'Documento Liquidacion',
  `NumeLiqu` int(20) DEFAULT '0',
  `ConsDeFa` int(11) DEFAULT '0',
  `UsuaAsis` varchar(20) DEFAULT '',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  KEY `idx_hojamate_codiinst_consadmi_codimate_numeorde` (`CodiInst`,`ConsAdmi`,`CodiMate`,`NumeOrde`),
  KEY `idx_HojaMate_ConsAdmi` (`CodiInst`,`ConsAdmi`),
  KEY `idx_HojaMate_inst_admi_conshoma` (`CodiInst`,`ConsAdmi`,`ConsHoMa`),
  KEY `idx_HojaMate_UnidMate` (`UnidMate`),
  PRIMARY KEY (`CodiInst`,`ConsAdmi`,`ConsHoMa`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `HojaLAdm`;
CREATE TABLE `HojaLAdm` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001' COMMENT 'Codigo Institucion',
  `ConsAdmi` varchar(12) NOT NULL DEFAULT '' COMMENT 'Consecutivo de Admision',
  `ConsHoLi` int(3) NOT NULL DEFAULT '0' COMMENT 'Consecutivo Hoja de Liquidos',
  `CodiModu` int(2) NOT NULL DEFAULT '0' COMMENT 'Codigo Modulo',
  `CodiServ` char(3) DEFAULT '0' COMMENT 'Codigo del Servicio',
  `FechPlan` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha Planeado Aplicacion',
  `HoraPlan` time NOT NULL DEFAULT '00:00:00' COMMENT 'Hora Planeado Aplicacion',
  `FechInic` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha en que Inicio Aplicacion',
  `HoraInic` time NOT NULL DEFAULT '00:00:00' COMMENT 'Hora en que Inicio Aplicacion de Oxigeno',
  `FechFina` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha Final de Aplicacion',
  `HoraFina` time NOT NULL DEFAULT '00:00:00' COMMENT 'Hora Final de Aplicacion',
  `CodiLiqu` varchar(20) DEFAULT NULL COMMENT 'Codigo de Liquidacion',
  `UnidMedi` int(1) NOT NULL DEFAULT '0' COMMENT 'Unidad de Medida de Liquido',
  `UnidFact` int(1) DEFAULT '0',
  `ViaAdmi` int(1) DEFAULT NULL COMMENT 'Via Administracion',
  `IndiAdic` varchar(255) DEFAULT NULL COMMENT 'Indicaciones Adicionales',
  `EsFact` int(1) DEFAULT NULL COMMENT 'Es Facturable',
  `UsuaAsis` varchar(12) DEFAULT '' COMMENT 'Usuario Asistencial',
  `EstaApli` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Codigo Institucion',
  `CantIndi` double NOT NULL DEFAULT '0',
  `CantApli` double NOT NULL DEFAULT '0' COMMENT 'Cantidad Aplicada',
  `CantFact` double NOT NULL DEFAULT '0' COMMENT 'Cantidad Facturada',
  `NumeOrde` int(20) DEFAULT '0' COMMENT 'Numero de Orden Global de la Prescripcion',
  `Item` int(2) DEFAULT '0' COMMENT 'Codigo Institucion',
  `CentCost` varchar(6) NOT NULL DEFAULT '0',
  `CodiDocu` varchar(4) DEFAULT '' COMMENT 'Documento Liquidacion',
  `NumeLiqu` int(20) DEFAULT '0' COMMENT 'Codigo Institucion',
  `ConsDeFa` int(11) DEFAULT '0',
  `DispLiqu` int(20) DEFAULT '0',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  KEY `idx_hojaladm` (`CodiInst`,`ConsAdmi`,`NumeOrde`,`CodiLiqu`),
  KEY `idx_HojaLAdm_admi` (`CodiInst`,`ConsAdmi`,`CodiLiqu`),
  KEY `idx_hojaladm_codiinst_consadmi_codiliqu_numeorde` (`CodiInst`,`ConsAdmi`,`CodiLiqu`,`NumeOrde`),
  KEY `idx_HojaLAdm_CodiLiqu` (`CodiLiqu`),
  KEY `idx_HojaLAdm_ConsAdmi` (`CodiInst`,`ConsAdmi`),
  KEY `idx_HojaLAdm_inst_admi_consholi` (`CodiInst`,`ConsAdmi`,`ConsHoLi`),
  PRIMARY KEY (`CodiInst`,`ConsAdmi`,`ConsHoLi`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `EvolInte`;
CREATE TABLE `EvolInte` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001' COMMENT 'Codigo Institucion',
  `ConsAdmi` varchar(12) NOT NULL DEFAULT '' COMMENT 'Consecutivo de Admision',
  `ConsEvol` int(2) NOT NULL COMMENT 'Consecutivo Evolucion',
  `CodiModu` int(2) NOT NULL DEFAULT '0' COMMENT 'Codigo Modulo',
  `FechEvol` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha Evolucion',
  `HoraEvol` time NOT NULL DEFAULT '00:00:00' COMMENT 'Hora Evolucion',
  `CodiProc` varchar(15) DEFAULT '' COMMENT 'Codigo de la consulta para evolucion',
  `NumeOrde` int(20) DEFAULT '0' COMMENT 'Numero de Orden',
  `Item` int(2) DEFAULT '0' COMMENT 'Numero de Item',
  `CodiDocu` varchar(4) DEFAULT '' COMMENT 'Documento Liquidacion',
  `NumeLiqu` int(20) DEFAULT '0' COMMENT 'Numero de Liquidacion',
  `ConsDeFa` int(20) DEFAULT '0' COMMENT 'Consecutivo Detalle de Liquidacion',
  `Subjetivo` text COMMENT 'Subjetivo',
  `Objetivo` text COMMENT 'Objetivo',
  `CodiDiag` char(8) DEFAULT '' COMMENT 'Diagnostico Principal',
  `CodiRel1` char(8) DEFAULT '' COMMENT 'Diagnostico relacionado 1',
  `CodiRel2` char(8) DEFAULT '' COMMENT 'Diagnostico relacionado 2',
  `CodiRel3` char(8) DEFAULT '' COMMENT 'Diagnostico relacionado 3',
  `CodiRel4` char(8) DEFAULT '' COMMENT 'Diagnostico relacionado 4',
  `TipoDiag` int(1) DEFAULT '0' COMMENT 'Tipo diagnostico',
  `TipoDiag1` int(1) DEFAULT '0' COMMENT 'Tipo diagnostico',
  `TipoDiag2` int(1) DEFAULT '0' COMMENT 'Tipo diagnostico',
  `TipoDiag3` int(1) DEFAULT '0' COMMENT 'Tipo diagnostico',
  `TipoDiag4` int(1) DEFAULT '0' COMMENT 'Tipo diagnostico',
  `Analisis` text COMMENT 'Analisis',
  `ContSign` int(1) NOT NULL DEFAULT '0' COMMENT 'Control de Signos Vitales Si/No',
  `ContLiqu` int(1) NOT NULL DEFAULT '0' COMMENT 'Control de Liquidos Si/No',
  `ContRevi` int(1) DEFAULT '0' COMMENT 'Campo para validar si ha sido revisado o no la evoluciÃ³n por un especialista
agregado el dÃ­a 08-03-2017',
  `MediRevi` varchar(12) DEFAULT '' COMMENT 'Indica el usuario (mÃƒÆ’Ã‚Â©dico especialista) que da check en el revisado de la evoluciÃƒÆ’Ã‚Â³n',
  `CentCost` varchar(6) DEFAULT '' COMMENT 'Centro de costos',
  `ServEgre` varchar(6) DEFAULT '' COMMENT 'Servicio de egreso ',
  `FechRevi` date DEFAULT '0000-00-00' COMMENT 'Fecha que indica cuando fue revisada la evoluciÃ³n del paciente',
  `HoraRevi` time DEFAULT '00:00:00' COMMENT 'Hora de revisado de la evoluciÃ³n',
  `DescRevi` text COMMENT 'DescripciÃ³n o anotaciÃ³n agregada por el mÃ©dico que revisa la evoluciÃ³n del paciente',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  `PlanMane` text,
  `CodiServ` varchar(6) DEFAULT '' COMMENT 'Servicio de egreso ',
  KEY `idx_evolinte_codiinst_consadmi_codidocu_codiproc` (`CodiInst`,`ConsAdmi`,`CodiDocu`,`CodiProc`),
  KEY `idx_EvolInte_ConsAdmi` (`CodiInst`,`ConsAdmi`),
  KEY `idx_EvolInte_inst_admi_evol` (`CodiInst`,`ConsAdmi`,`ConsEvol`),
  KEY `idx_evolinte_revi` (`ConsAdmi`,`ContRevi`,`ConsEvol`),
  PRIMARY KEY (`CodiInst`,`ConsAdmi`,`ConsEvol`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `TrasCama`;
CREATE TABLE `TrasCama` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001',
  `ConsAdmi` varchar(12) NOT NULL DEFAULT '',
  `ConsTras` int(2) NOT NULL DEFAULT '0',
  `CodiServ` char(3) NOT NULL,
  `CodiModu` int(3) DEFAULT '0' COMMENT 'Modulo',
  `CamaOrig` varchar(10) NOT NULL DEFAULT '',
  `ServEgre` char(3) NOT NULL,
  `EntoAten_id` bigint(20) DEFAULT NULL COMMENT 'Entorno de atencion id',
  `CamaDest` varchar(10) DEFAULT '',
  `FechIngr` date NOT NULL DEFAULT '0000-00-00',
  `HoraIngr` time NOT NULL DEFAULT '00:00:00',
  `FechSali` date NOT NULL DEFAULT '0000-00-00',
  `HoraSali` time NOT NULL DEFAULT '00:00:00',
  `Dias` double DEFAULT '0',
  `Horas` double DEFAULT '0',
  `CoinDest` varchar(12) DEFAULT '' COMMENT 'Codigo institucion referencia',
  `CoadDest` varchar(12) DEFAULT '' COMMENT 'Admision institucion referencia',
  `CentEgre` varchar(6) DEFAULT '' COMMENT 'Centro de costos de destino ',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  KEY `CodiModu` (`CodiModu`),
  KEY `idx_TrasCama_admi_modu` (`ConsAdmi`,`CodiModu`),
  KEY `idx_TrasCama_CamaOrig` (`CodiInst`,`CamaOrig`),
  KEY `idx_TrasCama_ConsAdmi` (`CodiInst`,`ConsAdmi`),
  PRIMARY KEY (`CodiInst`,`ConsAdmi`,`ConsTras`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `Remision`;
CREATE TABLE `Remision` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001',
  `ConsAdmi` varchar(12) NOT NULL,
  `CodiRemi` int(2) NOT NULL,
  `ConsAuto` int(3) DEFAULT '0' COMMENT 'Numero de Consecutivo de la Autorizacion',
  `CodiModu` int(2) NOT NULL,
  `MotiRemi` text,
  `EspeRemi` char(3) DEFAULT '',
  `InstRemi` varchar(10) DEFAULT '',
  `NombAcep` varchar(80) DEFAULT '',
  `CargAcep` varchar(40) DEFAULT NULL COMMENT 'Cargo de la Persona que Acepta la Remision del Paciente',
  `NumeAuto` varchar(15) DEFAULT '',
  `Ambulanc` int(1) NOT NULL DEFAULT '0' COMMENT 'Remision con Ambulancia',
  `PlacAmbu` varchar(10) DEFAULT NULL,
  `ModaSoli` int(2) NOT NULL,
  `RemiMoti` int(2) NOT NULL,
  `OtroMoti` text NOT NULL,
  `FechAcep` date DEFAULT '0000-00-00' COMMENT 'Fecha de aceptacion',
  `HoraAcep` time DEFAULT '00:00:00' COMMENT 'Hora de aceptacion',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  `TipoRemi` int(3) DEFAULT '0',
  `FechSali` date DEFAULT '0000-00-00',
  `HoraSali` time DEFAULT '00:00:00',
  `FechLLega` date DEFAULT '0000-00-00',
  `HoraLLega` time DEFAULT '00:00:00',
  `FechCier` date DEFAULT '0000-00-00',
  `HoraCier` time DEFAULT '00:00:00',
  `UsuaCier` varchar(20) DEFAULT '',
  `Cerrado` int(2) DEFAULT '0',
  `DiagRemi` char(8) DEFAULT '' COMMENT 'Diagnostico de remisiÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â³n',
  `DiagRel1` char(8) DEFAULT '' COMMENT 'Diagnostico relacionado 1',
  `DiagRel2` char(8) DEFAULT '' COMMENT 'Diagnostico relacionado 2',
  `DiagRel3` char(8) DEFAULT '' COMMENT 'Diagnostico relacionado 3',
  `DiagRel4` char(8) DEFAULT '' COMMENT 'Diagnostico relacionado 4',
  `DiagComp` char(8) DEFAULT '' COMMENT 'Diagnostico de complicacion',
  `TipoDiag` varchar(50) DEFAULT '',
  `TipoDia1` varchar(50) DEFAULT '',
  `TipoDia2` varchar(50) DEFAULT '',
  `TipoDia3` varchar(50) DEFAULT '',
  `TipoDia4` varchar(50) DEFAULT '',
  KEY `idx_Remision_ConsAdmi` (`CodiInst`,`ConsAdmi`),
  KEY `idx_Remision_InstRemi` (`CodiInst`,`InstRemi`),
  KEY `idx_Remision_ModaSoli` (`ModaSoli`),
  KEY `idx_Remision_PlacAmbu` (`PlacAmbu`),
  KEY `idx_Remision_RemiMoti` (`RemiMoti`),
  PRIMARY KEY (`CodiInst`,`ConsAdmi`,`CodiRemi`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `IncaPaci`;
CREATE TABLE `IncaPaci` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001',
  `ConsAdmi` varchar(12) NOT NULL DEFAULT '',
  `ConsInca` int(11) NOT NULL DEFAULT '1',
  `CodiModu` int(2) NOT NULL DEFAULT '0',
  `FechInca` date NOT NULL DEFAULT '0000-00-00',
  `HoraInca` time NOT NULL DEFAULT '00:00:00',
  `TipoInca` int(1) NOT NULL DEFAULT '1',
  `OrigInca` int(1) DEFAULT NULL COMMENT 'Origen de la incapacidad 1=Comun 2=Laboral',
  `DiasInca` int(10) DEFAULT NULL,
  `ObseInca` text,
  `TipoAlca` int(20) DEFAULT '0',
  `EmbaMult` int(10) DEFAULT '0',
  `CertNaVi` text,
  `NaciVivo` int(10) DEFAULT NULL,
  `CodIncRetro` int(2) DEFAULT NULL,
  `CodGrupServ` int(2) DEFAULT NULL,
  `CodMosPresServ` int(2) DEFAULT NULL,
  `FePoPart` date DEFAULT '0000-00-00' COMMENT 'Fecha probable de parto',
  `EdadGest` int(2) DEFAULT '0' COMMENT 'edad gestacional',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  KEY `FK_IncaPaci_GrupServ` (`CodGrupServ`),
  KEY `FK_IncaPaci_IncaRetro` (`CodIncRetro`),
  KEY `FK_IncaPaci_PresServ` (`CodMosPresServ`),
  PRIMARY KEY (`CodiInst`,`ConsAdmi`,`ConsInca`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `SaliInte`;
CREATE TABLE `SaliInte` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001',
  `ConsAdmi` varchar(12) NOT NULL DEFAULT '',
  `CodiModu` int(2) NOT NULL DEFAULT '0',
  `FechSali` date NOT NULL DEFAULT '0000-00-00',
  `HoraSali` time NOT NULL DEFAULT '00:00:00',
  `DiasEsta` int(3) DEFAULT NULL,
  `HoraEsta` int(2) DEFAULT NULL,
  `CausSali` int(1) DEFAULT NULL,
  `DestSali` char(2) DEFAULT NULL,
  `DiasInca` int(2) DEFAULT NULL,
  `DiagEgre` char(8) DEFAULT '' COMMENT 'Diagnostico de egreso',
  `DiagRel1` char(8) DEFAULT '' COMMENT 'Diagnostico relacionado 1',
  `DiagRel2` char(8) DEFAULT '' COMMENT 'Diagnostico relacionado 2',
  `DiagRel3` char(8) DEFAULT '' COMMENT 'Diagnostico relacionado 3',
  `DiagRel4` char(8) DEFAULT '' COMMENT 'Diagnostico relacionado 4',
  `DiagComp` char(8) DEFAULT '' COMMENT 'Diagnostico de complicacion',
  `TipoDiag` int(1) DEFAULT '0' COMMENT 'Tipo de diagnostico egreso',
  `TipoDia1` int(1) DEFAULT '0' COMMENT 'Tipo de diagnostico relacionado1',
  `TipoDia2` int(1) DEFAULT '0' COMMENT 'Tipo de diagnostico relacionado2',
  `TipoDia3` int(1) DEFAULT '0' COMMENT 'Tipo de diagnostico relacionado3',
  `TipoDia4` int(1) DEFAULT '0' COMMENT 'Tipo de diagnostico complicacion',
  `EstaSali` int(1) DEFAULT NULL,
  `DiagMuer` varchar(4) DEFAULT NULL,
  `FechMuer` date DEFAULT '0000-00-00',
  `HoraMuer` time DEFAULT '00:00:00',
  `ObseSali` text COMMENT 'Observacion de la Salida',
  `CodiProf` varchar(12) DEFAULT '',
  `UnidEdad` char(1) NOT NULL DEFAULT 'A',
  `ValoEdad` int(3) NOT NULL DEFAULT '0',
  `ServEgre` char(3) DEFAULT NULL,
  `CodiCama` varchar(10) DEFAULT NULL,
  `TipoEgre` int(1) DEFAULT '0',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  KEY `idx_saliinte_CausSali` (`CausSali`),
  KEY `idx_saliinte_codicama` (`CodiInst`,`CodiCama`),
  KEY `idx_saliinte_DestSali` (`DestSali`),
  KEY `idx_SaliInte_DiagEgre` (`DiagEgre`),
  KEY `idx_saliinte_fechsali_codiinst_consadmi` (`FechSali`,`CodiInst`,`ConsAdmi`),
  KEY `idx_SaliInte_inst_consadmi` (`CodiInst`,`ConsAdmi`),
  PRIMARY KEY (`CodiInst`,`ConsAdmi`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

SET FOREIGN_KEY_CHECKS=1;
