-- Catalogos (se llenan desde SIHOS por la app)
-- Generado desde sihosrecuperacion (copia de SIHOS) el 2026-09-25.
-- MISMOS nombres y columnas que SIHOS para poder exportar. Solo estructura, sin datos.
-- Sin llaves foraneas: la app inserta en orden padre -> hijo.

SET NAMES latin1;
SET SESSION sql_mode = 'NO_ENGINE_SUBSTITUTION';  -- SIHOS usa fechas 0000-00-00
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `AdmiEstr`;
CREATE TABLE `AdmiEstr` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001' COMMENT 'Codigo Institucion',
  `CodiAdmi` varchar(6) NOT NULL COMMENT 'Codigo Administradora',
  `TiDoTerc` char(2) NOT NULL DEFAULT '' COMMENT 'Tipo Documento Tercero',
  `NuDoTerc` varchar(20) DEFAULT '' COMMENT 'Numero Documento Tercero',
  `CodiEstr` char(1) NOT NULL COMMENT 'Categoria o Nivel',
  `TipoAten` int(1) NOT NULL COMMENT 'Tipo de Atencion',
  `TipoAfil` char(1) NOT NULL COMMENT 'Tipo de Afiliacion',
  `Copago` decimal(20,2) NOT NULL COMMENT 'Copago en procentaje',
  `Cuota` decimal(20,2) NOT NULL COMMENT 'Cuota en Valores Fijos',
  `ValoMaxi` decimal(20,2) NOT NULL COMMENT 'Valor Maximo a pagar por el usuario en esa categoria por año',
  `EstaEstr` int(1) NOT NULL DEFAULT '1' COMMENT 'Etado de la Categoria',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha de Creacion de la Categoria',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00' COMMENT 'Hora de Creacion de la Categoria',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha de ultima Modificacion del registro',
  `HoraModi` time NOT NULL DEFAULT '00:00:00' COMMENT 'Hora de ultima Modificacion del registro',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  KEY `CodiInst` (`CodiInst`,`CodiAdmi`,`CodiEstr`,`TipoAten`,`TipoAfil`),
  KEY `EstaEstr` (`EstaEstr`),
  KEY `idx_AdmiEstr_admi_inst_estr` (`CodiAdmi`,`CodiInst`,`CodiEstr`),
  KEY `idx_AdmiEstr_admi_inst_tipo` (`CodiAdmi`,`CodiInst`,`TipoAfil`),
  KEY `idx_AdmiEstr_CodiAdmi` (`CodiAdmi`),
  KEY `idx_AdmiEstr_CodiEstr` (`CodiEstr`),
  KEY `idx_AdmiEstr_CodiInst` (`CodiInst`),
  KEY `idx_AdmiEstr_EstaEstr` (`EstaEstr`),
  KEY `idx_AdmiEstr_TipoAfil` (`TipoAfil`),
  KEY `idx_AdmiEstr_TipoAten` (`TipoAten`),
  PRIMARY KEY (`CodiInst`,`CodiAdmi`,`CodiEstr`,`TipoAten`,`TipoAfil`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `CausExte`;
CREATE TABLE `CausExte` (
  `CodiMoti` char(2) NOT NULL DEFAULT '' COMMENT 'Codigo Causa',
  `NombMoti` varchar(30) DEFAULT '' COMMENT 'Nombre de la Causa',
  `CausExteSisPro` int(2) DEFAULT NULL,
  `ValoDefe` int(1) NOT NULL DEFAULT '0' COMMENT 'Causa por Defecto para los Formularios',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  KEY `CausExteSisPro` (`CausExteSisPro`),
  PRIMARY KEY (`CodiMoti`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `CausMorb`;
CREATE TABLE `CausMorb` (
  `id` bigint(20) NOT NULL auto_increment COMMENT 'Identificador único del registro',
  `CodiDiag` char(8) NOT NULL DEFAULT '' COMMENT 'Codigo de diagnostico',
  `NombCaus` varchar(255) NOT NULL COMMENT 'Nombre Causa o Diagnostico',
  `DescCie` text COMMENT 'Descripcion del diagnostico',
  `VersCie` int(1) DEFAULT '2' COMMENT 'Version Cie 1.CIEX, 2.CIEXI',
  `HomoDiag` bigint(20) unsigned DEFAULT NULL,
  `SexoCaus` char(1) NOT NULL COMMENT 'Sexo para ese Diagnostico segun tabla CodiSexo',
  `EdadMini` int(6) DEFAULT NULL COMMENT 'Edad Minima para ese Diagnostico',
  `EdadMaxi` int(6) DEFAULT NULL COMMENT 'Edad Maxima para ese Diagnostico',
  `ClasDiag` int(1) DEFAULT NULL COMMENT 'Clase de Diagnostico',
  `Nivel` int(1) DEFAULT NULL COMMENT 'Nivel de Complejidad del Diagnostico',
  `EnfeNoti` int(1) DEFAULT '0' COMMENT 'Es una Enferemedad de Notificacion 1/2',
  `DiagPrin` varchar(1) DEFAULT '1',
  `DiagRela` varchar(1) DEFAULT '1',
  `ClasCie` int(1) DEFAULT '3' COMMENT 'Clasificacion del diagnostico 1.Morbilidad 2. Mortalidad 3. Ambos',
  `CodiForm` int(1) DEFAULT '0' COMMENT 'Codigo del formulario de Sivigila(Tabla Sivigila.CodiForm)',
  `ProtSivi` varchar(200) DEFAULT '' COMMENT 'Protocolo definido por el I.N.S para el Diagnostico',
  `PlanEnfe` varchar(200) DEFAULT '' COMMENT 'Plan de Cuidados de Enfermeria',
  `RequTrat` int(3) DEFAULT '0' COMMENT 'diagnostico que requiere tratamiento. asociado a CodiTrat',
  `Ira` int(1) DEFAULT '0',
  `Eda` int(1) DEFAULT '0',
  `Varicela` int(11) DEFAULT '0' COMMENT 'Indica si el DX aplica a ficha colectiva de Varicela',
  `Chikungu` int(11) DEFAULT '0' COMMENT 'Indica si el DX aplica a ficha colectiva de Chikunguña',
  `Activo` int(1) DEFAULT '1' COMMENT 'Se Encuentra Activa la Causa',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  `CodiHuerf` varchar(50) DEFAULT '',
  `deleted_at` timestamp DEFAULT NULL COMMENT 'EliminaciÃ³n lÃ³gica del registro',
  `Huerfana` varchar(50) DEFAULT '',
  KEY `CodiDiag` (`CodiDiag`),
  KEY `CodiForm` (`CodiForm`),
  KEY `idx_CausMorb_ClasDiag` (`ClasDiag`),
  KEY `idx_CausMorb_EnfeNoti` (`EnfeNoti`),
  KEY `idx_CausMorb_Nivel` (`Nivel`),
  KEY `idx_CausMorb_PlanEnfe` (`PlanEnfe`),
  KEY `idx_CausMorb_SexoCaus` (`SexoCaus`),
  PRIMARY KEY (`CodiDiag`),
  UNIQUE KEY `uk_causmorb_id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `CeCoServ`;
CREATE TABLE `CeCoServ` (
  `CodiServ` varchar(3) NOT NULL,
  `CodiCent` varchar(6) NOT NULL,
  `Activo` int(1) DEFAULT '0' COMMENT 'Estado del centro de costo en la unidad funcional',
  `ActiDefe` int(1) DEFAULT '0' COMMENT 'Centro de costo por defecto',
  `FechDigi` date DEFAULT '0000-00-00',
  `HoraDigi` time DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date DEFAULT '0000-00-00',
  `HoraModi` time DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  KEY `FK_CeCoServ_CodiServ` (`CodiServ`),
  PRIMARY KEY (`CodiCent`,`CodiServ`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `ClasTria`;
CREATE TABLE `ClasTria` (
  `CodiTria` int(1) NOT NULL DEFAULT '0' COMMENT 'Codigo de Clase de Triage',
  `NombTria` varchar(255) DEFAULT NULL COMMENT 'Nombre de Clase de Triage',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  PRIMARY KEY (`CodiTria`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `CodiAdmi`;
CREATE TABLE `CodiAdmi` (
  `CodiAdmi` varchar(10) NOT NULL DEFAULT '' COMMENT 'Codigo Entidades Administradoras',
  `CodiAdm1` varchar(10) DEFAULT NULL COMMENT 'Codigo Entidades Administradoras para RIPS',
  `NombAdmi` varchar(100) NOT NULL COMMENT 'Nombre Entidad Administradora',
  `TiDoTerc` char(2) NOT NULL DEFAULT '' COMMENT 'Tipo de Documento del Tercero',
  `NitAdmin` varchar(20) DEFAULT NULL COMMENT 'Nit de Administradora en el Archivo de Terceros',
  `DepaAdmi` char(2) NOT NULL COMMENT 'Departamento de Administradora',
  `MuniAdmi` char(3) NOT NULL COMMENT 'Municipio de Administradora',
  `TipoAdmi` int(1) NOT NULL COMMENT 'Tipo Administradora',
  `DireAdmi` varchar(50) DEFAULT NULL COMMENT 'Direccion Administradora',
  `TeleAdmi` varchar(10) DEFAULT NULL COMMENT 'Telefono Administradora',
  `FaxAdmin` varchar(10) DEFAULT NULL COMMENT 'Fax Administradora',
  `MailAdmi` varchar(60) DEFAULT NULL COMMENT 'E-mail Administradora',
  `LlavPriv` text COMMENT 'Ruta de la llave privada',
  `EstaAdmi` int(1) NOT NULL DEFAULT '1' COMMENT 'Estado Administradora',
  `NombCont` varchar(100) DEFAULT '' COMMENT 'Nombre de contacto en la entidad',
  `TeleCont` varchar(20) DEFAULT '' COMMENT 'Telefono Contacto de la Entidad',
  `MailCont` varchar(60) DEFAULT '' COMMENT 'Mail del Contacto',
  `ReprLega` varchar(100) DEFAULT '' COMMENT 'Nombre del representante legal',
  `NoCir030` int(1) NOT NULL DEFAULT '1' COMMENT 'Reportar Administradora en Circular 030',
  `EsSoat` int(1) NOT NULL COMMENT 'Check para marcar si la administradora es Soat',
  `CodVeri` int(1) NOT NULL COMMENT 'Check para enviar en el asunto del correo de facturacion el codigo de verificacion',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  KEY `idx_CodiAdmi` (`CodiAdmi`),
  KEY `idx_CodiAdmi_EstaAdmi` (`EstaAdmi`),
  KEY `idx_CodiAdmi_MuniAdmi` (`DepaAdmi`,`MuniAdmi`),
  KEY `idx_CodiAdmi_TidoTerc_NitAdmin` (`CodiAdmi`,`TiDoTerc`,`NitAdmin`),
  KEY `idx_CodiAdmi_TipoAdmi` (`TipoAdmi`),
  PRIMARY KEY (`CodiAdmi`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `CodiCama`;
CREATE TABLE `CodiCama` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001' COMMENT 'Codigo Institucion',
  `CodiCama` varchar(10) NOT NULL DEFAULT '' COMMENT 'Codigo Cama',
  `NombCama` varchar(30) NOT NULL COMMENT 'Nombre de la Cama',
  `CodiServ` char(3) NOT NULL DEFAULT '' COMMENT 'Codigo de Servicio de la Cama',
  `CodiProc` varchar(15) NOT NULL DEFAULT '' COMMENT 'Codigo del Procedimiento',
  `ConsAdmi` varchar(12) DEFAULT '' COMMENT 'Consecutivo de Admision Actual en Cama',
  `ReseCama` int(11) DEFAULT NULL COMMENT 'Codigo de reserva de la cama',
  `DCO` double NOT NULL DEFAULT '0' COMMENT 'Dias Camas Ocupadas para el Reporte',
  `DCD` double NOT NULL DEFAULT '0' COMMENT 'Dias Camas Disponibles para el Reporte',
  `EsCirugi` int(1) NOT NULL DEFAULT '0' COMMENT 'Es una Cama de Cirugia',
  `Virtual` int(2) DEFAULT '0' COMMENT 'Es una Cama Virtual',
  `Es2193` char(1) DEFAULT NULL,
  `Activa` int(1) NOT NULL DEFAULT '1' COMMENT 'Cama Activa 1/2',
  `Habilita` int(2) DEFAULT '0' COMMENT 'Campo guardar si se habilita la cama',
  `EsUci` int(1) NOT NULL COMMENT 'Es Uci Furips',
  `Sexo` int(11) DEFAULT '0',
  `Edad` int(11) DEFAULT '0',
  `Oxigeno` int(11) DEFAULT '0',
  `TipoCama` int(11) DEFAULT '0',
  `ObseCama` varchar(50) DEFAULT '',
  `Estado` varchar(50) DEFAULT '',
  `TipoAisla` varchar(50) DEFAULT '',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  `TipoEgre` int(2) DEFAULT '0' COMMENT 'Tipo de egreso',
  KEY `idx_codicama_codicama` (`CodiCama`),
  KEY `idx_CodiCama_CodiInst` (`CodiInst`),
  KEY `idx_CodiCama_CodiProc` (`CodiProc`),
  KEY `idx_CodiCama_CodiServ` (`CodiServ`),
  KEY `idx_CodiCama_ConsAdmi` (`ConsAdmi`),
  KEY `idx_CodiCama_inst_serv_activa` (`CodiInst`,`CodiServ`,`Activa`,`NombCama`),
  PRIMARY KEY (`CodiInst`,`CodiCama`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `CodiDepa`;
CREATE TABLE `CodiDepa` (
  `CodiDepa` char(2) NOT NULL DEFAULT '',
  `NombDepa` varchar(50) NOT NULL DEFAULT '',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  `pais_id` bigint(20) NOT NULL DEFAULT '48' COMMENT 'País (FK CodiPais.id)',
  KEY `idx_tutabla_pais_id` (`pais_id`),
  PRIMARY KEY (`CodiDepa`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `CodiEspe`;
CREATE TABLE `CodiEspe` (
  `CodiEspe` char(3) NOT NULL,
  `NombEspe` varchar(100) NOT NULL,
  `GrupEspe` varchar(2) NOT NULL,
  `DuraCita` int(11) DEFAULT NULL,
  `EsProgra` int(1) DEFAULT '2' COMMENT 'La especialidad es progrmable en citas web',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  KEY `CodiEspe` (`CodiEspe`),
  KEY `NombEspe` (`NombEspe`),
  PRIMARY KEY (`CodiEspe`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `CodiEstr`;
CREATE TABLE `CodiEstr` (
  `CodiEstr` char(1) NOT NULL DEFAULT '',
  `NombEstr` varchar(20) NOT NULL DEFAULT '',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  PRIMARY KEY (`CodiEstr`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `CodiInst`;
CREATE TABLE `CodiInst` (
  `Id` bigint(20) NOT NULL auto_increment COMMENT 'Identificador Ãºnico',
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001' COMMENT 'Codigo de la Institucion',
  `NombInst` varchar(80) DEFAULT '' COMMENT 'Nombre de la Institucion',
  `NombGene` varchar(80) DEFAULT '' COMMENT 'Nombre General de la InstituciÃƒÂ³n',
  `TipoIden` char(2) DEFAULT NULL COMMENT 'Tipo de Identificacion',
  `NitInsti` varchar(20) DEFAULT NULL COMMENT 'Nit de la Institucion',
  `SedePrin` int(1) DEFAULT NULL COMMENT 'Es Sede Principal',
  `ConfSede` varchar(25) DEFAULT '' COMMENT 'Confirmacion de Sede',
  `CeduGere` varchar(20) DEFAULT NULL COMMENT 'Documento del Gerente',
  `NombGere` varchar(50) DEFAULT NULL COMMENT 'Nombre del Gerente',
  `NuDoAdmi` varchar(20) DEFAULT NULL COMMENT 'Documento del Administrador',
  `NombAdmi` varchar(50) DEFAULT NULL COMMENT 'Nombre del Administrador',
  `TPReviFi` varchar(20) DEFAULT NULL COMMENT 'Documento del Revisor Fiscal',
  `ReviFisc` varchar(50) DEFAULT NULL COMMENT 'Nombre del Revisor Fiscal',
  `TPContad` varchar(20) DEFAULT NULL COMMENT 'Documento del Contador',
  `NombCont` varchar(50) DEFAULT NULL COMMENT 'Nombre del Contador',
  `NumeDoPr` varchar(20) DEFAULT NULL COMMENT 'Documento del Jefe de Presupuesto',
  `NombPres` varchar(50) DEFAULT NULL COMMENT 'Nombre del Jefe de presupuesto',
  `NumeDoNo` varchar(20) DEFAULT NULL COMMENT 'Documento del Jefe de Nomina',
  `NombNomi` varchar(50) DEFAULT NULL COMMENT 'Nombre del Jefe de Nomina',
  `NumeDoTe` varchar(20) DEFAULT NULL COMMENT 'Numero del Documento del Tesorero',
  `NombTeso` varchar(50) DEFAULT NULL COMMENT 'Nombre del Tesorero',
  `NumeTaHu` varchar(20) DEFAULT '' COMMENT 'Numero del Documento de Resp. Talento Humano',
  `NombTaHu` varchar(50) DEFAULT '' COMMENT 'Nombre del Resp. Talento Humano',
  `CodiDepa` char(2) NOT NULL DEFAULT '' COMMENT 'Departamento',
  `CodiMuni` char(3) NOT NULL DEFAULT '' COMMENT 'Municipio',
  `DireInst` varchar(40) DEFAULT NULL COMMENT 'Direccion de Institucion',
  `TeleInst` varchar(10) DEFAULT NULL COMMENT 'Telefono de la Institucion',
  `MailInst` varchar(50) DEFAULT NULL,
  `WebInst` varchar(50) DEFAULT '' COMMENT 'Sitio Web de la Institucion',
  `FaxInst` varchar(15) DEFAULT NULL COMMENT 'Fax de Institucion',
  `FechCrea` date DEFAULT '2009-01-01' COMMENT 'Fecha de Creacion',
  `ActoAdmi` int(11) NOT NULL COMMENT 'Acto Administrativo de Creacion',
  `NumeActo` varchar(15) DEFAULT NULL COMMENT 'Numero de Acto',
  `FechActo` date DEFAULT NULL COMMENT 'Fecha del Acto',
  `CodiUnio` int(11) DEFAULT NULL COMMENT 'Codigo Presentacion de Informes',
  `ClasEnti` int(1) DEFAULT NULL COMMENT 'Clase de Entidad',
  `NatuJuri` int(1) DEFAULT '1' COMMENT 'Naturaleza Juridica de la Institucion',
  `ContTipo` int(1) DEFAULT '0' COMMENT 'Tipo de Contribuyente',
  `ActiEcon` varchar(5) DEFAULT '1' COMMENT 'Actividad Economica',
  `CaraEnti` int(11) DEFAULT '4' COMMENT 'Caracter de la Entidad',
  `RutaLogo` varchar(50) DEFAULT NULL COMMENT 'Ruta Logo de la Entidad',
  `CodiNive` int(2) NOT NULL DEFAULT '1' COMMENT 'Nivel de Complejidad de la Entidad',
  `TipoPers` int(2) DEFAULT '2' COMMENT 'Tipo Persona',
  `EsAutoRe` int(1) DEFAULT NULL COMMENT 'Es Autoretenedor',
  `EsGranCo` int(1) DEFAULT NULL COMMENT 'Es Gran Contribuyente',
  `EsReteFu` int(1) DEFAULT NULL COMMENT 'Agente retenedor ReteFuente',
  `EsReteIc` int(1) DEFAULT NULL COMMENT 'Agente retenedor de ICA',
  `ManeCost` char(1) DEFAULT '0' COMMENT 'Maneja Costos',
  `AnnoNIIF` char(4) DEFAULT '0' COMMENT 'Anno Para el Balance de Apertura NIIF',
  `ManeNIIF` int(1) DEFAULT '0' COMMENT 'Maneja NIIF',
  `PresGlob` int(1) NOT NULL DEFAULT '1' COMMENT 'Presupuesto Global',
  `ManePac` int(1) NOT NULL DEFAULT '2' COMMENT 'Maneja PAC',
  `ManeMoPe` int(1) DEFAULT '1' COMMENT 'Maneja Modulo Periferico',
  `AjPoRete` varchar(16) DEFAULT NULL COMMENT 'Cuenta Ajuste Positivo en la Declaración de Impuestos',
  `AjNeRete` varchar(16) DEFAULT NULL COMMENT 'Cuenta Ajuste Negativo en la Declaración de Impuestos',
  `AuReCREE` varchar(16) DEFAULT '' COMMENT 'Cuenta Autorretención del CREE',
  `AuReCRPa` varchar(16) DEFAULT '' COMMENT 'Cuenta Autorretención del CREE por Pagar',
  `UtilEjer` varchar(16) DEFAULT '323001' COMMENT 'Utilidad del Ejercicio',
  `AntCapita` varchar(16) DEFAULT NULL COMMENT 'Anticipo de capita',
  `PerdEjer` varchar(16) DEFAULT '323002' COMMENT 'Perdida del Ejercicio',
  `PerdCont` varchar(16) DEFAULT '511160' COMMENT 'Contrapartida de la Perdida',
  `GanaCont` varchar(16) DEFAULT '431298' COMMENT 'Contrapartida de la Ganancia',
  `CuenLetr` varchar(16) NOT NULL DEFAULT '140990' COMMENT 'Cuenta para Letras',
  `CuenDepo` varchar(16) NOT NULL DEFAULT '140990' COMMENT 'Cuenta para Depositos sin Identificar',
  `CuenAbon` varchar(16) NOT NULL DEFAULT '' COMMENT 'Cuenta para Abonos de Pacientes',
  `DescVent` varchar(16) NOT NULL DEFAULT '43951201' COMMENT 'Cuenta para Descuentos en Ventas',
  `CuenGlos` varchar(16) NOT NULL DEFAULT '' COMMENT 'Cuenta para Aceptacion de Glosas de Periodos Anteriores',
  `CuenGlosAct` varchar(16) DEFAULT '' COMMENT 'Cuenta para Aceptacion de Glosas de Periodos Actuales',
  `CuenFond` varchar(16) NOT NULL DEFAULT '' COMMENT 'Cuenta de Situacion de Fondos',
  `CuenDiCo` varchar(16) DEFAULT '' COMMENT 'Cuenta contable para Traslado de Cartera a Dificil Cobro',
  `CuenCast` varchar(16) DEFAULT '' COMMENT 'Cuenta Contable para Conciliacion',
  `CastCart` varchar(16) DEFAULT '' COMMENT 'Cuenta para el castigo de Cartera NIIF',
  `CuenCopa` varchar(16) NOT NULL COMMENT 'Cuenta contable para cuotas de recuperacion',
  `CuenGiDi` varchar(16) NOT NULL COMMENT 'Cuenta contable para giros directos en caja',
  `CuenDeAn` varchar(16) DEFAULT '' COMMENT 'Cuenta contable para devolucion de facturas de vigencias anteriores',
  `CuenInFa` varchar(16) DEFAULT '' COMMENT 'Interese en FacturaciÃ³n',
  `CuenCaFa` varchar(16) DEFAULT '' COMMENT 'Otros Cargo FacturaciÃ³n',
  `CuenAjFa` varchar(16) DEFAULT '' COMMENT 'Ajuste de Valor FacturaciÃ³n',
  `ManeFaEl` int(1) DEFAULT '2' COMMENT 'Maneja facturaciÃ³n electronica 1 si, 2 no',
  `ManeDocEqui` varchar(2) DEFAULT '',
  `ManeNoEl` int(1) DEFAULT '2' COMMENT 'Maneja Nomina Electronica',
  `CodiPost` varchar(15) DEFAULT '' COMMENT 'Codigo Postal',
  `SucuNomb` varchar(100) DEFAULT '' COMMENT 'Sucursal Nombre',
  `NombSoft` varchar(100) DEFAULT '' COMMENT 'Nombre del Software registrado en la DIAN',
  `NombSoftDocEqui` varchar(100) DEFAULT '' COMMENT 'Nombre del Software registrado en la DIAN',
  `SoftId` varchar(100) DEFAULT '' COMMENT 'Identificador del software registrado en la DIAN',
  `SoftPin` varchar(100) DEFAULT '' COMMENT 'Pin del software dado por la DIAN',
  `TestSetId` varchar(100) DEFAULT '',
  `Publica` varchar(100) DEFAULT '',
  `FechFE` date DEFAULT '0000-00-00',
  `EmailAuto` varchar(100) DEFAULT '',
  `Hostt` varchar(20) DEFAULT '' COMMENT 'campo para el dominio de correo',
  `Portt` varchar(5) DEFAULT '' COMMENT 'Puerto de envio de correos',
  `Pass` varchar(50) DEFAULT '' COMMENT 'contraseÃ±a de envio de correos',
  `TipoDocuRips` char(2) DEFAULT NULL COMMENT 'Tipo de documento del gerente para autentificacion rips sispro',
  `NumeDocuRips` varchar(11) DEFAULT NULL COMMENT 'Numero de documento del gerente para autentificacion de rips sispro',
  `ContRips` varchar(50) DEFAULT NULL COMMENT 'Contraseña Rips sispro',
  `MecaValiRips` char(1) DEFAULT NULL COMMENT 'Mecanismo de validacion rips sispro',
  `REPS` tinyint(4) DEFAULT NULL COMMENT 'REPS',
  `TokenRipsJson` text COMMENT 'Token que se genera desde el Api del ministerio para poder hacer envio de ripsjson',
  `FechToken` datetime DEFAULT '0000-00-00 00:00:00' COMMENT 'fecha y hora del token de ripsjson para calcular en que momento generar otro token',
  `UrlApiFevRips` varchar(100) DEFAULT NULL COMMENT 'Url de Api Fev Rips',
  `NombSoftNomiElec` varchar(100) DEFAULT '' COMMENT 'Nombre software de nomina electronica',
  `SoftIdNomiElec` varchar(100) DEFAULT '' COMMENT 'Software ID de nomina electronica',
  `SoftPinNomiElec` varchar(100) DEFAULT '' COMMENT 'PIN nomina electronica',
  `TestSetIdNomiElec` varchar(100) DEFAULT '' COMMENT 'Test set id nomina electronica',
  `SoftIdDocEqui` varchar(100) DEFAULT '' COMMENT 'software id documento equivalente',
  `SoftPinDocEqui` varchar(100) DEFAULT '' COMMENT 'pin documento equivalente',
  `TestSetIdDocEqui` varchar(100) DEFAULT '' COMMENT 'test set id documento equivalente',
  `CuenAvan` varchar(16) DEFAULT '' COMMENT 'Cuenta contable para avances/anticipos',
  `CuenCaAn` varchar(16) DEFAULT '' COMMENT 'Cuenta contable para Castigo de Cartera de vigencias anteriores',
  `CuenDeAd` varchar(16) DEFAULT '' COMMENT 'Cuenta contable para las Deducciones Adicionales',
  `CuenApIn` varchar(16) DEFAULT '' COMMENT 'Cuenta Contable para el aprovechamiento de inventarios',
  `CuenDeIn` varchar(16) DEFAULT '' COMMENT 'Cuenta Contable para el deterioro de inventarios',
  `CuenObSu` varchar(16) DEFAULT '' COMMENT 'Cuenta contable para la obsolescencia de suministros',
  `CuenDiSo` varchar(16) DEFAULT '' COMMENT 'Cuenta contable para los diferidos de software',
  `CuDiSoGa` varchar(16) DEFAULT '' COMMENT 'Cuenta contable para los diferidos de software gasto',
  `CuenDiSe` varchar(16) DEFAULT '' COMMENT 'Cuenta contable para los diferidos de seguros',
  `CuDiSeGa` varchar(16) DEFAULT '' COMMENT 'Cuenta contable para los diferidos de seguros gasto',
  `CuenInte` varchar(16) DEFAULT '',
  `CuenCamb` varchar(16) DEFAULT '',
  `RubrCopa` varchar(20) DEFAULT NULL COMMENT 'Rubro para ingresos cuotas de recuperacion',
  `RubrDiCo` varchar(20) DEFAULT NULL COMMENT 'Rubro para ingresos cartera dificil cobro',
  `CodiCHIP` varchar(50) DEFAULT '0' COMMENT 'codigo chip de la entidad cuipo',
  `CuipSect` varchar(50) DEFAULT '0' COMMENT 'Codigo del sector para el cuipo',
  `CuipSePr` varchar(50) DEFAULT '0' COMMENT 'Seccion presupuestal para el cuipo',
  `ApiCita` int(1) DEFAULT '0' COMMENT 'que sedes manejan api citas whatsapp 1 SI 0 NO',
  `DescFact` varchar(16) NOT NULL DEFAULT '' COMMENT 'Cuenta de Descuentos en Facturacion',
  `PorcRDF` decimal(7,4) DEFAULT '0.0000' COMMENT 'Porcentaje Recargo Diurno Festivo',
  `PorcRDO` decimal(7,4) DEFAULT '0.0000' COMMENT 'Porcentaje Recargo Diurno Ordinario',
  `PorcRNF` decimal(7,4) DEFAULT '0.0000' COMMENT 'Porcentaje Recargo Nocturno Festivo',
  `PorcRNO` decimal(7,4) DEFAULT '0.0000' COMMENT 'Porcentaje Recargo Nocturno Ordinario',
  `PorcHEDO` decimal(7,4) DEFAULT '0.0000' COMMENT 'Porcentaje Hora Extra Diurna Ordinaria',
  `PorcHEDF` decimal(7,4) DEFAULT '0.0000' COMMENT 'Porcentaje Hora Extra Diruna Festiva',
  `PorcHENF` decimal(7,4) DEFAULT '0.0000' COMMENT 'Porcentaje Hora Extra Nocturna Festiva',
  `PorcHENO` decimal(7,4) DEFAULT '0.0000' COMMENT 'Porcentaje Hora Extra Nocturna Ordinaria',
  `PorcSaEm` decimal(7,4) DEFAULT '0.0000' COMMENT 'Porcentaje de Salud Empleado',
  `PorcSaPa` decimal(7,4) DEFAULT '0.0000' COMMENT 'Porcentaje de Salud Patrono',
  `PorcPeEm` decimal(7,4) DEFAULT '0.0000' COMMENT 'Porcentaje de Pension Empleado',
  `PorcPePa` decimal(7,4) DEFAULT '0.0000' COMMENT 'Porcentaje de Pension Patrono',
  `PorcCesa` decimal(10,6) DEFAULT '0.010000' COMMENT 'Porcentaje Cesantias',
  `InteCesa` decimal(7,4) DEFAULT '0.0100' COMMENT 'Porcentaje Intereses a las Cesantias',
  `PorcRiAd` decimal(7,4) DEFAULT NULL COMMENT 'Porcentaje ARP administrativo',
  `PorcRiOp` decimal(7,4) DEFAULT NULL COMMENT 'Porcentaje ARP operativo',
  `PorcRiEx` decimal(7,4) DEFAULT '0.0000' COMMENT 'Porcentaje ARP Internos',
  `PorcRiIn` decimal(7,4) DEFAULT '0.0000' COMMENT 'Porcentaje ARP Externos',
  `PoFoSoPe` decimal(7,4) NOT NULL DEFAULT '0.0000' COMMENT 'Porcentaje Fondo Solidaridad Pensional',
  `PorcCaja` decimal(7,4) DEFAULT '0.0400' COMMENT 'Porcentaje Caja de Compensacion',
  `PoReLaEx` varchar(100) DEFAULT '"' COMMENT 'Rentas laborales excentas',
  `MxRenExe` varchar(100) DEFAULT '"' COMMENT 'Excento de retefuente',
  `PorcICBF` decimal(7,4) DEFAULT '0.0300' COMMENT 'Porcentaje ICBF',
  `PorcSENA` decimal(7,4) DEFAULT '0.0200' COMMENT 'Porcentaje SENA',
  `PorcEsap` decimal(7,4) NOT NULL DEFAULT '0.0500' COMMENT 'Porcentaje ESAP',
  `PorcInst` decimal(7,4) NOT NULL DEFAULT '0.0100' COMMENT 'Porcentaje Instituto del Seguro Social',
  `BaseSuAl` decimal(20,2) DEFAULT NULL COMMENT 'Base para saber quienes tienen derecho a Subsidio de Alimentacion',
  `SubsAlim` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Valor Subsidio de Alimentacion',
  `AuxTrans` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Valor Auxilio de Transporte',
  `PorIBCSI` decimal(7,4) NOT NULL DEFAULT '0.0000' COMMENT 'Porcentaje IBC del Salario Integral',
  `SMMLV` decimal(20,2) NOT NULL DEFAULT '496900.00' COMMENT 'Salario Mínimo Mensual Vigente incluido en CodiAno',
  `ToMaDePe` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Tope Maximo para Depreciacion en el Mes',
  `AlimMaxi` decimal(10,2) DEFAULT '0.00' COMMENT 'Tope Maximo de Alimentación',
  `AlimValo` decimal(10,2) DEFAULT '0.00' COMMENT 'Valor del Subsisio de Alimentacion',
  `SaloAnte` decimal(10,2) DEFAULT '0.00' COMMENT 'Salario Minino Año Anterior',
  `ToMaDeVi` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Tope Maximo para Depreciacion en el Año',
  `VaCuAcCo` decimal(20,2) DEFAULT '0.00' COMMENT 'Valor Cuantia Activos de Control',
  `IvaGener` decimal(10,2) DEFAULT '19.00' COMMENT 'Procentaje Iva General',
  `ManIvaDe` char(2) DEFAULT '2' COMMENT 'Maneja Iva Descontable 1:si, 2:no',
  `IvaDesco` decimal(10,2) DEFAULT '19.00' COMMENT 'Procentaje Iva Deducible',
  `CuIvaDes` varchar(16) DEFAULT '' COMMENT 'Cuenta Iva Descontable',
  `UVT` decimal(20,2) DEFAULT '23763.00' COMMENT 'Valor de la UBT',
  `LimiReDe` decimal(3,0) NOT NULL DEFAULT '0' COMMENT 'Límite general de Rentas exentas y Deducciones',
  `LiReDeHa` decimal(10,0) NOT NULL DEFAULT '0' COMMENT 'Límite general de Rentas exentas y Deducciones',
  `PorcDeRe` decimal(10,2) DEFAULT '0.00' COMMENT 'Porcentaje de Base Exenta de Retefuente',
  `CodiCent` varchar(6) NOT NULL DEFAULT '' COMMENT 'Centro de Costo por Institucion',
  `TiDoARP` char(2) DEFAULT '' COMMENT 'Tipo de Documento de la ARP',
  `NuDoARP` varchar(20) DEFAULT '' COMMENT 'Numero de Documento de la ARP',
  `Activa` int(1) NOT NULL DEFAULT '0' COMMENT 'Porcentaje Recargo Diurno Festivo',
  `FechBloq` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha de Bloqueo total',
  `PassBloq` varchar(20) DEFAULT '' COMMENT 'clave para desbloqueo',
  `FactPro1` decimal(10,6) DEFAULT '0.000000' COMMENT 'Factor de Provision 1',
  `FactPro2` decimal(10,6) DEFAULT '0.000000' COMMENT 'Factor de Provision 2',
  `FactPro3` decimal(10,6) DEFAULT '0.000000' COMMENT 'Factor de Provision 3',
  `FactPro4` decimal(10,6) DEFAULT '0.000000' COMMENT 'Factor de Provision 4',
  `FactPro5` decimal(10,6) DEFAULT '0.000000' COMMENT 'Factor de Provision 5',
  `TopeBoni` decimal(10,2) DEFAULT '0.00' COMMENT 'Valor del tope maximo del salario para porcentaje de bonificación',
  `DoceCesa` int(1) DEFAULT '2' COMMENT 'Maneja Doceava de Cesantias=1 ',
  `PorceDTF` decimal(10,2) DEFAULT '0.00' COMMENT 'Porcentaje de DTF dado por el banco de la republica, el valor se utiliza para calcular la tasa de interes en cartera por edad y facturacion',
  `MostFirm` int(1) DEFAULT '2' COMMENT 'Mostrar firmas acorde al historico',
  `RuCuReGl` int(1) DEFAULT '0' COMMENT 'Rubro Cuotas de RecuperaciÃ³n Global',
  `RuDiCoGl` int(1) DEFAULT '0' COMMENT 'Rubro Dificil Cobro Global',
  `HabiNomEl` int(1) DEFAULT '2' COMMENT 'Ambiente Nomina Electronica (1 habilitaciÃ²n, 2 Pruebas)',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  UNIQUE KEY `Id` (`Id`),
  KEY `idx_CodiInst` (`CodiInst`),
  KEY `idx_CodiInst_ActiEcon` (`ActiEcon`),
  KEY `idx_CodiInst_ActoAdmi` (`ActoAdmi`),
  KEY `idx_CodiInst_CaraEnti` (`CaraEnti`),
  KEY `idx_CodiInst_ClasEnti` (`ClasEnti`),
  KEY `idx_CodiInst_CodiCent` (`CodiCent`),
  KEY `idx_CodiInst_CodiInst` (`CodiInst`),
  KEY `idx_CodiInst_CodiMuni` (`CodiDepa`,`CodiMuni`),
  KEY `idx_CodiInst_CodiNive` (`CodiNive`),
  KEY `idx_CodiInst_TipoPers` (`TipoPers`),
  PRIMARY KEY (`CodiInst`,`CodiCent`),
  KEY `SedePrin` (`SedePrin`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `CodiItem`;
CREATE TABLE `CodiItem` (
  `CodiItem` int(20) NOT NULL DEFAULT '0' COMMENT 'Codigo del Item',
  `CodiModu` int(2) DEFAULT NULL COMMENT 'Modulo del Item',
  `TipoObje` int(2) DEFAULT NULL COMMENT 'Tipo de Objeto de la Tabla TipoObje',
  `CodiSecc` int(3) DEFAULT NULL COMMENT 'Seccion de la Tabla CodiSecc',
  `Pregunta` varchar(240) DEFAULT NULL COMMENT 'Pregunta Abierta',
  `NumeOrde` int(3) DEFAULT NULL COMMENT 'Numero de Orden de la Pregunta',
  `CodiSino` int(1) DEFAULT NULL COMMENT 'Responde Si o No 1/2',
  `CodiEsta` int(1) DEFAULT '0',
  `Texto` int(1) DEFAULT NULL COMMENT 'Responde con Texto 1/2',
  `Valor1` int(1) DEFAULT NULL COMMENT 'Responde con Valor1 1/2',
  `Valor2` int(1) DEFAULT NULL COMMENT 'Responde con Valor2 1/2',
  `DefeSiNo` int(1) DEFAULT NULL COMMENT 'Defecto para Si o No 1/2',
  `DefeEsta` int(1) DEFAULT '0',
  `DefeText` text COMMENT 'Defecto para Texto',
  `DefeVal1` int(20) DEFAULT NULL COMMENT 'Defecto para el Valor1',
  `DefeVal2` int(20) DEFAULT NULL COMMENT 'Defecto para el Valor2',
  `ValoMini` decimal(10,2) DEFAULT NULL COMMENT 'Valor Minimo de Referencia',
  `ValoMaxi` decimal(10,2) DEFAULT NULL COMMENT 'Valor Maximo de Referencia',
  `RangMini` decimal(10,2) DEFAULT NULL COMMENT 'Rango Minimo Permitido para los Valores1y2',
  `RangMaxi` decimal(10,2) DEFAULT NULL COMMENT 'Rango Maximo Permitido para los Valores1y2',
  `Sexo` char(1) DEFAULT NULL COMMENT 'Sexo de acuero a CodiSexo para que aparezca la pregunta en la Historia',
  `EdadMini` int(3) DEFAULT NULL COMMENT 'Edad Minima para que aparezca la pregunta en la Historia Clinica',
  `EdadMaxi` int(3) DEFAULT NULL COMMENT 'Edad Maxima para que aparezca la pregunta en la Historia Clinica',
  `CondUsua` int(1) DEFAULT NULL COMMENT 'Condicion de la Usuaria para que aparezca en la Historia',
  `Activo` int(1) DEFAULT '1' COMMENT 'Activa la Pregunta 1=Si 2=No',
  `FechDigi` date DEFAULT '0000-00-00',
  `HoraDigi` time DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date DEFAULT '0000-00-00',
  `HoraModi` time DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  KEY `idx_CodiItem_CodiModu` (`CodiModu`),
  KEY `idx_CodiItem_Seccion` (`CodiSecc`),
  KEY `idx_CodiItem_TipoObje` (`TipoObje`),
  PRIMARY KEY (`CodiItem`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `CodiMuni`;
CREATE TABLE `CodiMuni` (
  `CodiDepa` char(2) NOT NULL,
  `CodiMuni` char(3) NOT NULL,
  `NombMuni` varchar(50) NOT NULL,
  `Mapa` varchar(40) DEFAULT '',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  KEY `CodiMuni` (`CodiMuni`),
  KEY `idx_CodiMuni_CodiDepa` (`CodiDepa`),
  PRIMARY KEY (`CodiDepa`,`CodiMuni`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `CodiPais`;
CREATE TABLE `CodiPais` (
  `id` bigint(20) NOT NULL auto_increment COMMENT 'Identificador único de la tabla',
  `CodiPais` char(3) NOT NULL DEFAULT '',
  `NombPais` varchar(50) NOT NULL DEFAULT '',
  `IsoPais` char(3) DEFAULT '',
  `CodiHL7pais` char(3) DEFAULT '' COMMENT ' ISO 3166-1 alpha3',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  UNIQUE KEY `id` (`id`),
  PRIMARY KEY (`CodiPais`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `CodiProc`;
CREATE TABLE `CodiProc` (
  `CodiProc` varchar(15) NOT NULL DEFAULT '' COMMENT 'Codigo del Procedimiento',
  `NombProc` varchar(254) DEFAULT NULL COMMENT 'Nombre del Procedimiento',
  `CodiCups` varchar(8) NOT NULL DEFAULT '' COMMENT 'Codigo CUPS',
  `CodiSoat` varchar(8) NOT NULL DEFAULT '' COMMENT 'Codigo SOAT',
  `CodiISS` varchar(8) NOT NULL DEFAULT '' COMMENT 'Codigo ISS',
  `SexoProc` char(1) DEFAULT NULL COMMENT 'Sexo del Procedimiento',
  `EdadMini` int(3) DEFAULT NULL COMMENT 'Edad Minima',
  `EdadMaxi` int(3) DEFAULT NULL COMMENT 'Edad Maxima',
  `TipoServ` int(2) NOT NULL DEFAULT '0' COMMENT 'Tipo de Servicio',
  `CentCost` varchar(6) DEFAULT NULL COMMENT 'Centro de Costo que lo Desarrolla',
  `tipo_tecnologia_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Identificador de la tecnologia en salud',
  `FinaProc` int(1) DEFAULT NULL COMMENT 'Finalidad del Procedimiento',
  `FinaCons` char(2) DEFAULT NULL COMMENT 'Finalidad de Consulta',
  `TipoActi` int(6) DEFAULT NULL COMMENT 'Tipo de Actividad POS o no POS',
  `Nivel` int(2) DEFAULT NULL COMMENT 'Nivel de Complejidad',
  `TipoProc` int(2) NOT NULL DEFAULT '0' COMMENT 'Tipo Procedimiento Odontologia/Otro',
  `CodiModa` char(2) DEFAULT NULL COMMENT 'Codigo de modalidad del procedimiento.',
  `EsProg` int(1) NOT NULL DEFAULT '0' COMMENT 'Es Programable o aparece en Citas',
  `CaMaOrde` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Cantidad Maxima Ordenada por Orden',
  `CaMaOrDi` decimal(20,2) DEFAULT '0.00' COMMENT 'Cantidad Maxima Ordenada por Dia',
  `CaMaOrMe` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Cantidad Maxima Ordenada por Mes',
  `CaMaFact` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Cantidad Maxima Permitida en Facturacion',
  `OrdeFact` int(1) DEFAULT '3' COMMENT 'Es Ordenable y/o Facturable',
  `AtSinLiq` int(1) DEFAULT '0' COMMENT 'atender actividad sin liquidar',
  `TipoIVA` int(2) NOT NULL DEFAULT '0' COMMENT 'Tipo IVA del Procedimiento',
  `Observac` varchar(200) DEFAULT NULL COMMENT 'Descripcion del Procedimiento',
  `Activo` int(1) NOT NULL DEFAULT '1' COMMENT 'Activo Si o No',
  `TrasCheck` int(1) NOT NULL COMMENT 'Check de Traslado Primario',
  `CodiEspe` int(11) DEFAULT '0' COMMENT 'Actividad para asignar api whatsapp',
  `TipoAtenSi` char(2) DEFAULT NULL COMMENT 'Codigo del grupo de servisio sispro',
  `ServSispro` char(50) DEFAULT '' COMMENT 'Codigo del servicio correspondiente al grupo de servicio sispro',
  `TrasChek` int(1) NOT NULL COMMENT 'Check de Traslado Primario',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  `HL7Codi` int(11) DEFAULT NULL,
  KEY `CodiCups` (`CodiCups`),
  KEY `CodiProc` (`CodiProc`),
  KEY `CodiProc_ibfk_3` (`TipoServ`),
  KEY `FinaCons` (`FinaCons`),
  KEY `idx_CodiProc_CentCost` (`CentCost`),
  KEY `idx_CodiProc_FinaProc` (`FinaProc`),
  KEY `idx_CodiProc_Nivel` (`Nivel`),
  KEY `idx_codiproc_servicio` (`CodiProc`,`Nivel`,`CodiCups`),
  KEY `idx_CodiProc_SexoProc` (`SexoProc`),
  KEY `idx_CodiProc_tipo` (`TipoServ`,`CodiProc`),
  KEY `idx_CodiProc_TipoActi` (`TipoActi`),
  KEY `idx_CodiProc_TipoIVA` (`TipoIVA`),
  KEY `idx_CodiProc_TipoProc` (`TipoProc`),
  KEY `idx_codiproc_tiposerv` (`CodiProc`,`TipoServ`),
  KEY `idx_tipo_tecnologia_id` (`tipo_tecnologia_id`),
  KEY `NombProc` (`NombProc`),
  KEY `OrdeFact` (`OrdeFact`),
  PRIMARY KEY (`CodiProc`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `CodiServ`;
CREATE TABLE `CodiServ` (
  `CodiServ` char(3) NOT NULL COMMENT 'Codigo del Servicio',
  `NombServ` varchar(50) NOT NULL COMMENT 'Nombre del Servicio',
  `CoSeSisP` int(4) DEFAULT '0',
  `TipoAten` int(1) NOT NULL DEFAULT '1' COMMENT 'Tipo de Atencion',
  `EsObserv` int(1) NOT NULL DEFAULT '0' COMMENT 'Es Observacion',
  `ValoDefe` int(1) NOT NULL DEFAULT '0' COMMENT 'Valor por Defecto en la Creacion de Admisiones Automaticas',
  `ClasServ` int(1) NOT NULL DEFAULT '0' COMMENT 'Clase de Servicio',
  `CausExte` char(2) DEFAULT NULL COMMENT 'Causa Externa por defecto cuando se elije este servicio en la Admision',
  `Activo` int(1) NOT NULL DEFAULT '1' COMMENT 'Activo',
  `DeriSisPro` char(5) NOT NULL DEFAULT '1' COMMENT 'derivado de ingreso',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  KEY `CodiServ` (`CodiServ`),
  KEY `CoSeSisP` (`CoSeSisP`),
  KEY `idx_codiserv_codiserv_tipoaten` (`CodiServ`,`TipoAten`),
  KEY `idx_CodiServ_TipoAten` (`TipoAten`),
  PRIMARY KEY (`CodiServ`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `CodiSumi`;
CREATE TABLE `CodiSumi` (
  `CodiSumi` varchar(20) NOT NULL DEFAULT '' COMMENT 'Codigo del Suministro',
  `CodiRips` varchar(20) NOT NULL DEFAULT '' COMMENT 'Codigo del Suministro para los RIPS',
  `expediente` varchar(20) NOT NULL DEFAULT '' COMMENT 'Expediente CUM',
  `IdenUniMedi_id` bigint(20) NOT NULL DEFAULT '0' COMMENT 'IUM',
  `PrincAct_id` int(5) DEFAULT NULL COMMENT 'DCI',
  `CodiEan` varchar(300) NOT NULL DEFAULT '' COMMENT 'Codigo de Barras',
  `CantDefe` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Cantidad por Defecto',
  `NombSumi` varchar(200) DEFAULT NULL COMMENT 'Nombre del Suministro',
  `DescRefe` varchar(50) DEFAULT '' COMMENT 'Descripcion o Referencia',
  `Contrain` text COMMENT 'Contraindicaciones al Suministro',
  `Recomend` text COMMENT 'Recomendaciones',
  `Posologi` text COMMENT 'Posologia',
  `Foto` varchar(100) DEFAULT '' COMMENT 'Fotografia del Producto o Activo',
  `CodiGrup` char(4) NOT NULL DEFAULT '' COMMENT 'Codigo del Grupo CodiGrup',
  `TipoServ` int(3) NOT NULL DEFAULT '0' COMMENT 'Tipo de Servicio',
  `TipoProd` int(11) DEFAULT '0' COMMENT 'Tipo de Producto',
  `CodiGene` varchar(20) DEFAULT NULL COMMENT 'Codigo del Generico CodiGene',
  `CodiCubs` varchar(16) DEFAULT NULL COMMENT 'Clasificacion Unica de Bienes y Servicios',
  `CodiCum` varchar(18) DEFAULT NULL COMMENT 'Clasificacion Unica de Medicamentos',
  `CodiLabo` varchar(15) DEFAULT NULL COMMENT 'Codigo de Laboratorio',
  `CentCost` varchar(6) NOT NULL DEFAULT '0' COMMENT 'Centro de Costo',
  `Desperdi` int(1) DEFAULT '0' COMMENT 'Se puede desperdiciar o no el insumo medicamento (1 = ACTIVO;0=INACTIVO)',
  `MediCont` int(1) DEFAULT '0' COMMENT 'Medio de contenciÃƒÂ³n del suministro',
  `CircPrec` int(1) DEFAULT '2' COMMENT 'Aplica resolución de precios de medicamentos.',
  `IdenDisp` varchar(12) NOT NULL DEFAULT '' COMMENT '.',
  `ViaAdmin` int(1) DEFAULT '1' COMMENT 'Via de administracion si es medicamento',
  `RegiInvi` varchar(50) NOT NULL DEFAULT '' COMMENT 'Registro Invima',
  `EsPyp` int(1) DEFAULT '0' COMMENT 'Es Suministro de PyP',
  `Marca` varchar(50) NOT NULL DEFAULT '' COMMENT 'Marca del Producto',
  `TopeMini` double NOT NULL DEFAULT '0' COMMENT 'Tope Minimo',
  `TopeMaxi` double NOT NULL DEFAULT '0' COMMENT 'Tope Máximo',
  `CodiUnid` char(2) DEFAULT NULL COMMENT 'Unidad Menor de Compra',
  `Contenid` varchar(50) NOT NULL DEFAULT '' COMMENT 'Contenido en Unidades de UnidMedi',
  `UnidMedi` int(1) NOT NULL DEFAULT '1' COMMENT 'Unidad de Distribucion Asistencial',
  `Unidad_Medida_id` bigint(20) DEFAULT NULL COMMENT 'Identificador de la unidad de medida',
  `FormFarm` char(2) DEFAULT NULL COMMENT 'Si es un Medicamento reuquerir Forma Farmaceutica',
  `ConcMedi` varchar(50) DEFAULT '' COMMENT 'Si es un Medicamento Concentracion del Medicamento',
  `CostoU` decimal(20,8) DEFAULT '0.00000000' COMMENT 'Costo Unitario',
  `CostoP` decimal(20,8) DEFAULT '0.00000000' COMMENT 'Costo Promedio',
  `TipoIVA` int(2) NOT NULL DEFAULT '0' COMMENT 'Tipo IVA',
  `CantPedi` decimal(20,2) DEFAULT '0.00' COMMENT 'Cantidad de Pedido',
  `ValoPedi` decimal(20,2) DEFAULT '0.00' COMMENT 'Valor en Pedido',
  `FechUlCo` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha Ultima Compra',
  `CantUlIn` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Cantidad de Ultimo Ingreso',
  `ValoUlIn` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Valor Ultimo Ingreso',
  `FechUlEn` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha Ultima Entrada',
  `CantUlEg` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Cantidad Ultima Salida',
  `ValoUlEg` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Valor Ultimo Egreso',
  `FechUlSa` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha Ultima Salida',
  `CantInfi` decimal(20,2) DEFAULT '0.00' COMMENT 'Cantidad de Inventario Final',
  `ValoInfi` decimal(20,8) DEFAULT '0.00000000' COMMENT 'Valor Inventario Final',
  `CaMaOrde` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Cantidad Maxima por Prescripcion',
  `CaMaOrMe` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Cantidad Maxima por Prescripcion en el Mes',
  `OrdeFact` int(1) DEFAULT '3' COMMENT 'Ordenado/Facturado',
  `tipo_tecnologia_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Identificador de la tecnologia en salud',
  `NumeSeri` varchar(30) NOT NULL,
  `ModeDevo` varchar(30) NOT NULL COMMENT 'Modelo del Devolutivo',
  `RotuDevo` varchar(30) NOT NULL COMMENT 'Rotulo del Devolutivo',
  `MediDevo` decimal(20,2) NOT NULL DEFAULT '1.00' COMMENT 'Medida del Devolutivo',
  `TipoTecn` int(11) DEFAULT '0' COMMENT 'Tipo de Tecnológia a la cual pertenece el equipo',
  `FechComp` date NOT NULL COMMENT 'Fecha de Compra del Devolutivo',
  `ValoComp` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Valor de Compra',
  `UltiDepr` date NOT NULL COMMENT 'Fecha de Ultima Depreciacion',
  `UltiValo` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Ultimo Valor o Valor Actual',
  `BodeActu` int(2) NOT NULL COMMENT 'Bodega Actual',
  `CodiServ` char(3) NOT NULL COMMENT 'Servicio de Origen',
  `TiDoReSe` char(2) NOT NULL COMMENT 'Tipo de Documento de Responsable',
  `NuDoReSe` varchar(20) NOT NULL COMMENT 'Numero de Documento de Responsable',
  `CodiDocu` varchar(3) NOT NULL COMMENT 'Documento de Ingreso o Entrada a Almacen',
  `NumeDocu` int(11) NOT NULL COMMENT 'Numero del Documento de Ingreso o Entrada a Almacen',
  `ConsDevo` int(25) NOT NULL COMMENT 'Consecutivo de Detalle que creo el producto',
  `EstaDevo` int(1) NOT NULL COMMENT 'Estado del Devolutivo',
  `CodiTerc` char(2) NOT NULL COMMENT 'Tipo Documento del Tercero',
  `NumeTerc` varchar(20) NOT NULL COMMENT 'Numero Documento del Tercero',
  `FechFact` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha de la Factura de Compra',
  `NumeFact` varchar(20) NOT NULL COMMENT 'Numero de la Factura de Compra',
  `FechEntr` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha de la Entrada del Activo',
  `PorcSalv` decimal(4,2) unsigned NOT NULL DEFAULT '0.00' COMMENT 'Porcentaje de Salvamento',
  `TiDoAseg` char(2) NOT NULL DEFAULT '' COMMENT 'Tipo de Documento de la Aseguradora',
  `NuDoAseg` varchar(15) NOT NULL DEFAULT '' COMMENT 'Numero de Documento de la Aseguradora',
  `NumePoli` varchar(20) NOT NULL DEFAULT '' COMMENT 'Numero de Poliza de la Aseguradora',
  `FechVida` date NOT NULL COMMENT 'Fecha de Salida al Servicio del Activo',
  `BienAjus` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Valor del Bien Ajustado',
  `AjInAcum` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Ajuste debido a Inflacion Acumulada',
  `DeprAcum` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Depreciacion Acumulada',
  `AjInDeAc` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Ajuste Inflacion por Depreciacion Acumulada',
  `DeAcAjIn` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Depreciacion Acumulada al Ajuste de Inflacion',
  `MeDeprec` int(5) NOT NULL COMMENT 'Meses ya Depreciados Inicia en 0',
  `TiemDepr` int(6) DEFAULT NULL COMMENT 'Dias Ya Depreciados Inicia en 0',
  `MeseDepr` int(5) NOT NULL COMMENT 'Meses Totales a Depreciar',
  `DiasDepr` int(6) NOT NULL COMMENT 'Dias Totales a Depreciar',
  `SumiActi` int(1) NOT NULL DEFAULT '1' COMMENT 'Activo Si/No',
  `FeSeNiif` date DEFAULT '0000-00-00' COMMENT 'Fecha de Salida al Servicio del Activo Bajo NIIF',
  `UlDeNiif` date DEFAULT '0000-00-00' COMMENT 'Fecha Ultima Depreciacion Bajo NIIF',
  `ViUtNiif` int(5) DEFAULT '0' COMMENT 'Vida Util de Activo Devolutivo en Meses Bajo NIIF',
  `MeDeNiif` int(5) DEFAULT '0' COMMENT 'Meses de Depreciacion Bajo NIIF',
  `DiDeNiif` int(6) DEFAULT '0' COMMENT 'Dias de Depreciacion Bajo NIIF',
  `MePdeNii` int(5) DEFAULT '0' COMMENT 'Meses Por Depreciar Bajo NIIF',
  `DiPdeNii` int(6) DEFAULT '0' COMMENT 'Dias por Depreciar Bajo NIIF',
  `CompNiif` decimal(20,2) DEFAULT '0.00' COMMENT 'Valor Compra Bajo NIIF',
  `DeAcNiif` decimal(20,2) DEFAULT '0.00' COMMENT 'Depreciacion Acumulada Bajo NIIF',
  `SalvNiif` decimal(20,2) DEFAULT '0.00' COMMENT 'Salvamento Bajo NIIF',
  `ValoSalv` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Valor de salvamento',
  `ActuNiif` decimal(20,2) DEFAULT '0.00' COMMENT 'Valor Actual Bajo NIIF',
  `CaMaFact` decimal(20,2) DEFAULT '0.00' COMMENT 'Cantidad Maxima Permitida en Facturacion',
  `CaMaLiqu` decimal(20,2) DEFAULT '0.00' COMMENT 'Cantidad Maxima por Liquidacion ',
  `CateSumi` int(2) DEFAULT '0' COMMENT 'Categoria del Suministro',
  `TeMiSumi` int(4) DEFAULT '0' COMMENT 'Temperatura minima',
  `TeMaSumi` int(4) DEFAULT '0' COMMENT 'temperatuira maxima',
  `CoLuzAlm` int(1) DEFAULT '0' COMMENT 'Condicion del Manejo de Luz 1:No Controlada 2:Controlada',
  `FormCome` int(2) DEFAULT '0' COMMENT 'Forma de Comercializacion 1: Comun, 2:Marca',
  `EsCompon` int(1) DEFAULT '2' COMMENT '1 = Si es un componente | 2 = No Es un componente',
  `CoSuPadr` varchar(20) DEFAULT '' COMMENT 'Si es un componente, se ingresa el CodiSumi del activo fijo padre',
  `EsDeteri` int(1) DEFAULT '2' COMMENT '1 = El activo fijo se encuentra deteriorado | 2 = El activo fijo no se ha deteriorado',
  `ValoDete` decimal(18,2) DEFAULT '0.00' COMMENT 'Valor acumulado deteriorado del activo fijo',
  `TipoDife` int(11) DEFAULT '0' COMMENT 'Tipo de diferido (1 Software ; 2 Seguro)',
  `FeUlDife` date DEFAULT '0000-00-00' COMMENT 'Fecha de ultima vez que fue diferido',
  `DifeAcum` decimal(20,2) DEFAULT '0.00' COMMENT 'Valor acumulado de diferido',
  `DifeViUt` int(11) DEFAULT '0' COMMENT 'Vida util del diferido en meses',
  `TipoMediPost` char(2) DEFAULT NULL COMMENT 'Tipo de medicamento Pos',
  `DescMagi` varchar(30) DEFAULT NULL COMMENT 'descripcion magistral',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha de Creacion',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00' COMMENT 'Hora Creacion',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha Ultima Modificacion',
  `HoraModi` time NOT NULL DEFAULT '00:00:00' COMMENT 'Hora Ultima Modificacion',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  `PrincAct` varchar(3) DEFAULT NULL,
  KEY `CantInfi` (`CantInfi`),
  KEY `expediente` (`expediente`),
  KEY `IdenUniMedi_id` (`IdenUniMedi_id`),
  KEY `idx_CodiSumi_CentCost` (`CentCost`),
  KEY `idx_CodiSumi_CodiCubs` (`CodiCubs`),
  KEY `idx_CodiSumi_CodiGrup` (`CodiGrup`),
  KEY `idx_CodiSumi_CodiUnid` (`CodiUnid`),
  KEY `idx_CodiSumi_depr` (`TipoProd`,`FechVida`,`UltiDepr`,`EstaDevo`),
  KEY `idx_CodiSumi_diferidos` (`TipoProd`,`TiDoReSe`,`NuDoReSe`,`FechComp`),
  KEY `idx_CodiSumi_FormFarm` (`FormFarm`),
  KEY `idx_CodiSumi_OrdeFact` (`OrdeFact`),
  KEY `idx_codisumi_tipo` (`CodiSumi`,`TipoProd`),
  KEY `idx_CodiSumi_TipoIVA` (`TipoIVA`),
  KEY `idx_CodiSumi_TipoProd` (`TipoProd`),
  KEY `idx_CodiSumi_TipoServ` (`TipoServ`),
  KEY `idx_CodiSumi_Unidad_Medida_id` (`Unidad_Medida_id`),
  KEY `idx_CodiSumi_UnidMedi` (`UnidMedi`),
  KEY `idx_tipo_tecnologia_id` (`tipo_tecnologia_id`),
  KEY `NombSumi` (`NombSumi`),
  PRIMARY KEY (`CodiSumi`),
  KEY `PrincAct_id` (`PrincAct_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `CondTria`;
CREATE TABLE `CondTria` (
  `CodiTipo` int(1) NOT NULL DEFAULT '1',
  `NombTipo` varchar(30) NOT NULL DEFAULT '',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  PRIMARY KEY (`CodiTipo`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `CondUsua`;
CREATE TABLE `CondUsua` (
  `CodiCond` int(1) NOT NULL auto_increment,
  `NombCond` varchar(30) NOT NULL DEFAULT '',
  `ValoDefe` int(1) NOT NULL DEFAULT '0',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  PRIMARY KEY (`CodiCond`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `Contrato`;
CREATE TABLE `Contrato` (
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001' COMMENT 'Codigo Institucion',
  `NumeCont` varchar(15) NOT NULL COMMENT 'Numero Interno del Contrato',
  `NumeCon1` varchar(25) NOT NULL COMMENT 'Numero del Contrato para los RIPS',
  `CodiAdmi` varchar(10) NOT NULL DEFAULT '' COMMENT 'Codigo Administradora',
  `TipoDocu` char(2) NOT NULL DEFAULT '' COMMENT 'Tipo Documento Tercero',
  `NumeTerc` varchar(20) NOT NULL DEFAULT '' COMMENT 'Numero Documento Tercero',
  `DescCont` varchar(100) DEFAULT NULL COMMENT 'Nombre o Descripcion del Contrato',
  `CodiManu` char(5) NOT NULL COMMENT 'Manual Tarifario',
  `CodiMaSu` char(5) NOT NULL,
  `CodiPlan` char(2) NOT NULL COMMENT 'Plan',
  `CoImProc` char(1) DEFAULT '' COMMENT 'Código de impresión de los procedimientos en la liquidación y factura 1. CUPS 2. SOAT 3. ISS',
  `CoImSumi` char(1) DEFAULT '' COMMENT 'Código de impresión de los suministros en la liquidación y factura 1. CUM 2. ATC ',
  `CodiImpr` char(1) DEFAULT '' COMMENT 'Código de impresión en la liquidación y factura 1. CUPS 2. SOAT 3. ISS',
  `FechCont` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha del Contrato',
  `FechInCo` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha de Inicio del Contrato',
  `FechFiCo` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha del Fin del Contrato',
  `EstaCont` int(1) NOT NULL DEFAULT '1' COMMENT 'Estado del Contrato',
  `Estado_id` bigint(20) unsigned DEFAULT NULL,
  `TipoUsua` int(1) NOT NULL COMMENT 'Tipo de Usuario del Contrato TipoUsua',
  `TipoCont` int(1) NOT NULL DEFAULT '1' COMMENT 'Tipo de Contrato Evento/Capitado TipoCont',
  `CantUsua` int(20) NOT NULL DEFAULT '0' COMMENT 'Cantidad de Usuarios en la Capita',
  `ValoIndi` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Valor por Persona en la Capita',
  `ValoCont` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Valor Total del Contrato',
  `TopeIndi` double DEFAULT NULL COMMENT 'Maximo a Facturar por Usuario',
  `TopeTota` double DEFAULT NULL COMMENT 'Maximo a Facturar por este Contrato',
  `CodiDocu` char(3) NOT NULL DEFAULT '' COMMENT 'Codigo Documento Comprobante de Egreso',
  `FactIndi` int(1) DEFAULT '2' COMMENT 'Elabora Automaticamente Factura Individual',
  `DiaVenc` int(2) DEFAULT '10' COMMENT 'Numero de Dias Estimados de Vencimiento a partir de la Fecha de Expedicion',
  `PorcInEf` decimal(20,5) DEFAULT '0.00000' COMMENT 'Porcentaje de Interes Efectivo cartera vencida',
  `Alerta` int(1) NOT NULL DEFAULT '0' COMMENT 'Alerta Si/No',
  `FactMesu` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Alerta al LLegar a este Valor',
  `Bloqueo` int(1) NOT NULL DEFAULT '0' COMMENT 'Bloqueo Si/No',
  `FactMaxi` decimal(20,2) NOT NULL DEFAULT '0.00' COMMENT 'Valor Maximo Facturable de Bloqueo',
  `Nivel` int(2) DEFAULT '5' COMMENT 'Nivel de Complejidad',
  `PlanBene` varchar(2) NOT NULL COMMENT 'Cobertura o plan de beneficios',
  `FacSinCont` varchar(10) DEFAULT NULL COMMENT 'CÃ³digo causal de facturaciÃ³n sin contrato. Fuente: tabla facturaSinContrato SISPRO (prv_lista_tipo_id = 42). Obligatorio cuando CUCON estÃ© vacÃ­o.',
  `PiePagin` text NOT NULL COMMENT 'Pie de pagina para impresion en la factura',
  `AsunEmai` varchar(100) NOT NULL DEFAULT '' COMMENT 'Asunto para envio de facturacion electronica',
  `FormaPago` int(2) DEFAULT '0' COMMENT 'Forma de pago',
  `FormPago` int(2) NOT NULL DEFAULT '0' COMMENT 'Forma de pago',
  `MetoPago` int(2) NOT NULL DEFAULT '0' COMMENT 'Metodo de pago',
  `Siifa_id` bigint(20) DEFAULT NULL COMMENT 'Referencia al contrato en SIIFA',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  KEY `CodiInst` (`CodiInst`,`CodiAdmi`,`NumeCont`),
  KEY `fk_contrato_estado_id` (`Estado_id`),
  KEY `idx_CodiInst` (`CodiInst`),
  KEY `idx_CodiInst_CodiAdmi_CodiManu_CodiPlan` (`CodiInst`,`CodiAdmi`,`CodiManu`,`CodiPlan`),
  KEY `idx_CodiInst_TipoCont` (`CodiInst`,`TipoCont`),
  KEY `idx_CodiManu_CodiPlan` (`CodiManu`,`CodiPlan`),
  KEY `idx_Contrato_busqueda` (`CodiInst`,`CodiAdmi`,`TipoCont`,`EstaCont`,`TipoUsua`,`NumeCont`),
  KEY `idx_Contrato_CodiAdmi` (`CodiAdmi`),
  KEY `idx_Contrato_CodiInst_CodiAdmi_NumeCont` (`CodiInst`,`CodiAdmi`,`NumeCont`),
  KEY `idx_Contrato_CodiManu` (`CodiManu`),
  KEY `idx_contrato_codinst_codiadmi_numcont` (`CodiInst`,`CodiAdmi`,`NumeCont`),
  KEY `idx_Contrato_CodiPlan` (`CodiPlan`),
  KEY `idx_contrato_codi_admi` (`CodiAdmi`),
  KEY `idx_contrato_codi_inst` (`CodiInst`),
  KEY `idx_contrato_codi_manu` (`CodiManu`),
  KEY `idx_contrato_codi_plan` (`CodiPlan`),
  KEY `idx_Contrato_EstaCont` (`EstaCont`),
  KEY `idx_contrato_numecont_tipocont` (`CodiInst`,`CodiAdmi`,`NumeCont`,`TipoCont`),
  KEY `idx_Contrato_TipoCont` (`TipoCont`),
  KEY `idx_Contrato_TipoUsua` (`TipoUsua`),
  KEY `idx_contrato_tipo_cont` (`TipoCont`),
  KEY `idx_siifa_id` (`Siifa_id`),
  KEY `idx_TipoCont` (`TipoCont`),
  PRIMARY KEY (`CodiInst`,`CodiAdmi`,`NumeCont`),
  KEY `reporte_facturacion_idx_contrato_join` (`CodiInst`,`NumeCont`,`CodiAdmi`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `Paciente`;
CREATE TABLE `Paciente` (
  `TipoDocu` char(2) NOT NULL DEFAULT '' COMMENT 'Tipo Documento',
  `NumeUsua` varchar(20) NOT NULL DEFAULT '' COMMENT 'Numero de Usuario',
  `NumeCarn` varchar(15) DEFAULT NULL COMMENT 'Numero de Carne',
  `NumeHist` varchar(22) DEFAULT NULL COMMENT 'Numero de Historia',
  `NombUsua` varchar(20) DEFAULT NULL,
  `NombUsu1` varchar(20) DEFAULT NULL,
  `AplNomIde` int(1) NOT NULL DEFAULT '0' COMMENT 'Aplica nombre identitario',
  `NomIdeInt` varchar(100) DEFAULT NULL COMMENT 'Nombre identitario del paciente',
  `ModIdeInt` timestamp DEFAULT NULL COMMENT 'Fecha y hora de modificaciÃ³n de Nombre identitario',
  `UsuModIde` varchar(8) DEFAULT NULL COMMENT 'Usuario que modificÃ³ el Nombre identitario',
  `Ape1Usua` varchar(30) DEFAULT NULL,
  `Ape2Usua` varchar(30) DEFAULT NULL,
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001' COMMENT 'Institucion del Contrato',
  `CodiAdmi` varchar(6) DEFAULT NULL COMMENT 'Codigo Administradora',
  `TiDoTerc` char(2) NOT NULL DEFAULT '' COMMENT 'Tipo Documento del Tercero',
  `NuDoTerc` varchar(20) NOT NULL DEFAULT '' COMMENT 'Numero del Documento del Tercero',
  `TipoUsua` int(1) DEFAULT NULL COMMENT 'Tipo de Usuario',
  `TipoAfil` char(1) NOT NULL DEFAULT '' COMMENT 'Tipo de Afiliacion',
  `TipDocCo` char(2) DEFAULT '' COMMENT 'Tipo Documento Cotizante en esta misma Base de Datos',
  `NumUsuCo` varchar(20) DEFAULT '' COMMENT 'Numero Documento Cotizante en esta misma Base de Datos',
  `EstrPaci` char(1) DEFAULT NULL COMMENT 'Categoria del Paciente',
  `NumeCont` varchar(15) DEFAULT NULL COMMENT 'Numero de Contrato',
  `TipoAten` int(1) DEFAULT NULL COMMENT 'Tipo de Atencion',
  `Ocupacio` int(4) DEFAULT '9998' COMMENT 'Ocupacion',
  `EncuSisb` int(1) DEFAULT '0' COMMENT 'Encuesta del SISBEN 0= sin dato, 1= Encuestado 2 = Sin encuestar, ',
  `PuntSisb` float(4,2) DEFAULT '0.00' COMMENT 'Puntaje Encuesta del SISBEN',
  `NiveEsco` int(2) DEFAULT '1' COMMENT 'Nivel de escolaridad',
  `GrupoAte` char(4) DEFAULT NULL,
  `PertEtni` int(2) DEFAULT '6' COMMENT 'Pertenencia Etnica',
  `CabeFami` int(1) DEFAULT '2' COMMENT 'Es Cabeza de Familia',
  `FechNaci` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha de Nacimiento',
  `HoraNaci` time NOT NULL DEFAULT '00:00:00' COMMENT 'Hora de Nacimiento',
  `SexoUsua` char(1) DEFAULT NULL COMMENT 'Sexo',
  `GeneUsua` char(1) DEFAULT NULL COMMENT 'Genero',
  `OrieSexu` char(2) DEFAULT NULL COMMENT 'Orientación Sexual',
  `IdenGene` char(3) DEFAULT NULL COMMENT 'Identidad de Genero',
  `EstaCivi` char(1) DEFAULT NULL COMMENT 'Estado Civil',
  `CodiPais` char(3) DEFAULT '169' COMMENT 'Codigo Pais de Nacionalidad',
  `OrigDepa` char(2) DEFAULT '' COMMENT 'Departamento de Origen',
  `OrigMuni` char(3) DEFAULT '' COMMENT 'Municipio de Origen',
  `ResiDepa` char(2) NOT NULL DEFAULT '' COMMENT 'Departamento de Residencia',
  `ResiMuni` char(3) NOT NULL DEFAULT '' COMMENT 'Municipio de Residencia',
  `ResiComu` char(3) NOT NULL DEFAULT '' COMMENT 'Comuna de Residencia',
  `ResiZona` char(1) NOT NULL DEFAULT '' COMMENT 'Zona de Residencia',
  `ResiBarr` char(3) NOT NULL DEFAULT '' COMMENT 'Barrio de Residencia',
  `DireResi` varchar(80) DEFAULT NULL,
  `CodiPost` varchar(50) DEFAULT '',
  `TeleResi` varchar(12) DEFAULT NULL COMMENT 'Telefono de Residencia',
  `TeleCelu` varchar(12) DEFAULT '' COMMENT 'Telefono Celular',
  `SinNumTele` varchar(12) DEFAULT '',
  `MotiNullCel` varchar(100) DEFAULT NULL,
  `Email` varchar(60) DEFAULT NULL,
  `VeriMail` int(2) DEFAULT NULL COMMENT 'verificacion de email',
  `Token` varchar(50) DEFAULT NULL,
  `NombPadr` varchar(80) DEFAULT NULL,
  `NombMadr` varchar(80) DEFAULT NULL,
  `RespPaci` varchar(80) DEFAULT NULL,
  `TeleResp` varchar(20) DEFAULT '' COMMENT 'Telefono del Responsable del paciente',
  `PareResp` int(2) DEFAULT '0' COMMENT 'Parentesco del Responsable del paciente',
  `RH` int(1) NOT NULL DEFAULT '0' COMMENT 'Tipo de Sangre',
  `TipoDisc` int(2) DEFAULT '0' COMMENT 'Tipo de Discapacidad',
  `EsquVacu` int(1) DEFAULT '0' COMMENT 'Esquema de vacunacion completo',
  `Activo` int(1) DEFAULT '1' COMMENT 'Activo Si o No',
  `NullCel` int(1) DEFAULT NULL COMMENT 'Sin Telefono ',
  `FechActi` date DEFAULT '0000-00-00' COMMENT 'Fecha de inactivacion del paciente',
  `HoraActi` time DEFAULT '00:00:00' COMMENT 'Hora de inactivacion del paciente',
  `UsuaActi` varchar(12) DEFAULT '' COMMENT 'Usuario que inactiva el paciente',
  `Foto` longblob COMMENT 'Foto',
  `Huella` mediumblob,
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  `PaisResi` char(3) NOT NULL DEFAULT '170' COMMENT 'Codigo Pais de residencia',
  KEY `idx_Paciente_Ape1Usua` (`Ape1Usua`),
  KEY `idx_Paciente_Ape2Usua` (`Ape2Usua`),
  KEY `idx_Paciente_buscar` (`NumeUsua`,`NomIdeInt`,`NombUsua`,`NombUsu1`,`Ape1Usua`,`Ape2Usua`,`TipoDocu`,`ResiDepa`,`ResiMuni`),
  KEY `idx_Paciente_CodiInst` (`CodiInst`,`CodiAdmi`,`NumeCont`),
  KEY `idx_Paciente_CodiInst_2` (`CodiInst`,`CodiAdmi`,`EstrPaci`,`TipoAten`,`TipoAfil`),
  KEY `idx_Paciente_CodiPais` (`CodiPais`),
  KEY `idx_Paciente_EstaCivi` (`EstaCivi`),
  KEY `idx_Paciente_GrupoAte` (`GrupoAte`),
  KEY `idx_Paciente_NombUsu1` (`NombUsu1`),
  KEY `idx_Paciente_NombUsua` (`NombUsua`),
  KEY `idx_Paciente_NomIdeInt` (`NomIdeInt`),
  KEY `idx_Paciente_NumeUsua` (`NumeUsua`),
  KEY `idx_Paciente_Ocupacio` (`Ocupacio`),
  KEY `idx_Paciente_ResiBarr` (`ResiBarr`,`ResiComu`,`ResiMuni`,`ResiDepa`,`ResiZona`),
  KEY `idx_Paciente_ResiDepa` (`ResiDepa`),
  KEY `idx_Paciente_ResiDepa_ResiMuni` (`ResiDepa`,`ResiMuni`),
  KEY `idx_Paciente_RH` (`RH`),
  KEY `idx_Paciente_SexoUsua` (`SexoUsua`),
  KEY `idx_Paciente_TipoDocu` (`TipoDocu`),
  KEY `idx_Paciente_TipoUsua` (`TipoUsua`),
  KEY `Paciente_ibfk_13` (`TipoDisc`),
  KEY `Paciente_ibfk_9` (`ResiDepa`,`ResiMuni`,`ResiComu`,`ResiZona`,`ResiBarr`),
  PRIMARY KEY (`TipoDocu`,`NumeUsua`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `TipoUsua`;
CREATE TABLE `TipoUsua` (
  `CodiTipo` int(2) NOT NULL DEFAULT '0',
  `NombTipo` varchar(100) NOT NULL,
  `CodiInst` varchar(12) NOT NULL DEFAULT '868650001001',
  `CodiPlan` varchar(20) DEFAULT NULL,
  `CodiPla1` varchar(20) DEFAULT NULL,
  `CodiAno` char(4) DEFAULT NULL,
  `CodiCont` varchar(16) DEFAULT NULL,
  `CodiRadi` varchar(16) DEFAULT NULL COMMENT 'Cuenta Contable para la facturacion radicada segun res 421 de 2011',
  `DeteAcum` varchar(16) DEFAULT '' COMMENT 'Cuenta contable para el deterioro acumulado',
  `DeteEdad` varchar(16) DEFAULT '' COMMENT 'Cuenta contable para el deterioro por edades (si hay deterioro amortizado se deja vacio)',
  `CodiTrDi` varchar(16) DEFAULT '' COMMENT 'Cuenta contable para el traslado de dificil cobro',
  `Supersa` varchar(2) DEFAULT NULL,
  `GlosDebe` varchar(16) NOT NULL DEFAULT '',
  `GlosHabe` varchar(16) NOT NULL DEFAULT '',
  `Regi4505` int(1) NOT NULL DEFAULT '0' COMMENT 'Tipo de regimen para reportar en la resolucion 4505',
  `Decr2193` int(1) DEFAULT NULL COMMENT 'Regimen decreto 2193',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  `CodiTipoHL7` int(2) DEFAULT '0',
  `TipoUsuaSisPro` char(2) DEFAULT NULL,
  KEY `idx_TipoUsua_CodiCont` (`CodiCont`),
  KEY `idx_TipoUsua_CodiInst` (`CodiInst`),
  KEY `idx_TipoUsua_CodiPlan` (`CodiPlan`),
  PRIMARY KEY (`CodiTipo`),
  KEY `TipoUsuaSisPro` (`TipoUsuaSisPro`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `Usuarios`;
CREATE TABLE `Usuarios` (
  `CC` varchar(15) NOT NULL DEFAULT '',
  `Login` varchar(12) NOT NULL DEFAULT '',
  `CorrUsua` varchar(80) DEFAULT '' COMMENT 'Correo del usuario',
  `Nombre` varchar(70) NOT NULL,
  `Nom1Usua` varchar(30) DEFAULT '' COMMENT 'Primer Nombre Usuario',
  `Nom2Usua` varchar(30) DEFAULT '' COMMENT 'Segundo Nombre Usuario',
  `Ape1Usua` varchar(30) DEFAULT '' COMMENT 'Primer Apellido Usuario',
  `Ape2Usua` varchar(30) DEFAULT '' COMMENT 'Segundo Apellido Usuario',
  `Password` varchar(50) NOT NULL,
  `UsuaAsis` int(1) NOT NULL DEFAULT '1',
  `CodiEspe` char(3) DEFAULT NULL,
  `PersAtie` int(1) NOT NULL DEFAULT '5',
  `RegiProf` varchar(10) NOT NULL,
  `FechReso` date DEFAULT '0000-00-00' COMMENT 'Fecha de la resoluciÃƒÂ³n que autoriza el ejercicio profesional',
  `ConsUsua` int(4) NOT NULL DEFAULT '0',
  `Activo` int(1) NOT NULL DEFAULT '1',
  `TipoDocu` char(2) NOT NULL DEFAULT 'CC',
  `ManeTari` int(1) NOT NULL DEFAULT '2',
  `CodiManu` char(5) DEFAULT NULL,
  `FotoFirm` varchar(100) NOT NULL,
  `RespDefe` int(1) NOT NULL DEFAULT '2' COMMENT 'Responsable de entrega por defecto 1= Si, 2 = No.',
  `huella` mediumblob NOT NULL,
  `Foto` varchar(128) NOT NULL COMMENT 'Foto',
  `TipoLogu` int(1) DEFAULT '1' COMMENT 'Tipo de Logueo a Utilizar. 1=ContraseÃ±a + Huella, 2=Solo ContraseÃ±a, 3=Solo Huella',
  `AdmiSivi` int(1) DEFAULT '2' COMMENT 'Administrador Sivigila',
  `UsuaSiifa` varchar(30) DEFAULT NULL COMMENT 'Usuario para sistema SIIFA',
  `ContraSiifa` varchar(50) DEFAULT NULL COMMENT 'ContraseÃ±a para sistema SIIFA',
  `EstaSiifa` int(11) DEFAULT '2' COMMENT 'Estado de verificaciÃ³n de credenciales SIIFA',
  `ActiSiifa` int(11) DEFAULT '2' COMMENT 'Estado activo para el sistema SIIFA',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  `ValiEven` int(2) DEFAULT '1',
  KEY `CC` (`CC`),
  KEY `idx_Usuarios_cc_login_codiespe` (`CC`,`Login`,`CodiEspe`),
  KEY `idx_Usuarios_CodiEspe` (`CodiEspe`),
  KEY `idx_Usuarios_Login_CC` (`Login`,`CC`),
  KEY `idx_Usuarios_Login_CodiEspe` (`Login`,`CodiEspe`),
  KEY `idx_Usuarios_PersAtie` (`PersAtie`),
  KEY `Login` (`Login`),
  PRIMARY KEY (`Login`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `ViaAcces`;
CREATE TABLE `ViaAcces` (
  `CodiVia` int(1) NOT NULL auto_increment,
  `NombVia` varchar(40) NOT NULL DEFAULT '',
  `FechDigi` date NOT NULL DEFAULT '0000-00-00',
  `HoraDigi` time NOT NULL DEFAULT '00:00:00',
  `UsuaDigi` varchar(12) DEFAULT '' COMMENT 'Usuario Digito',
  `FechModi` date NOT NULL DEFAULT '0000-00-00',
  `HoraModi` time NOT NULL DEFAULT '00:00:00',
  `UsuaModi` varchar(12) DEFAULT '' COMMENT 'Usuario Modifico',
  PRIMARY KEY (`CodiVia`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

SET FOREIGN_KEY_CHECKS=1;
